// Build-time copy only. src/game is the single canonical rules implementation.
// The Edge Runtime serves files inside supabase/functions, so it needs this copy.
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.join(root, 'src/game');
const destination = path.join(root, 'supabase/functions/_shared/game');
await mkdir(destination, { recursive: true });
let count = 0;
for (const filename of await readdir(source)) {
  if (!filename.endsWith('.ts') || /\.(test|spec)\.ts$/.test(filename)) continue;
  const content = await readFile(path.join(source, filename), 'utf8');
  // Native Deno requires explicit extensions; Vite permits extensionless imports.
  const denoContent = content.replace(/(from\s+['"])(\.\.?\/[^'"]+)(['"])/g,
    (full, prefix, specifier, suffix) => path.extname(specifier) ? full : `${prefix}${specifier}.ts${suffix}`);
  await writeFile(path.join(destination, filename), `// Generated by supabase/sync-engine.mjs. Edit src/game/${filename}.\n${denoContent}`);
  count++;
}
console.log(`Synced ${count} game modules for Supabase Edge Functions.`);
await writeFile(path.join(root, 'supabase/functions/_shared/room-wire.ts'),
  '// Generated by supabase/sync-engine.mjs. Edit src/lib/room-wire.ts.\n' +
  await readFile(path.join(root, 'src/lib/room-wire.ts'), 'utf8'));
await writeFile(path.join(root, 'supabase/functions/_shared/countries.ts'),
  '// Generated by supabase/sync-engine.mjs. Edit src/lib/countries.ts.\n' +
  await readFile(path.join(root, 'src/lib/countries.ts'), 'utf8'));
