// Generated by supabase/sync-engine.mjs. Edit src/game/campaign.ts.
import { CHARACTERS, ROYAL_CHARACTERS } from './characters.ts';
import { MAPS, getMap } from './maps.ts';
import { validateHouseRules, CHAINS } from './engine.ts';
import { CHAIN_IDS, type GameConfig, type MapId, type HouseRules } from './types.ts';
import { royalAvatar } from './avatars.ts';

export interface StoryChapter {
  id: string; number: number; title: string; district: string; mapId: MapId; players: number;
  intro: string; victory: string; tip: string; opponents: string[];
  chapter: number; stage: number; strategy: string; houseRules: Partial<HouseRules>;
}
type ChapterSeed = [string, string, MapId, number, string, string, string];
const chapters: ChapterSeed[] = [
  ['Small change', 'The corner shop', 'duo-pocket-square', 2,
    'Your aunt leaves you a battered hotel ledger and one piece of advice: start small, think big. Penny has already claimed the best chair at the corner café. Win your first table and earn an invitation across town.',
    'Penny slides you a coupon marked ONE FRESH START. The city has noticed its newest investor.',
    'A cheap share can secure both bonuses when you are the only shareholder.'],
  ['A key, a biscuit, a plan', 'Moonlight mews', 'duo-moon-lock', 2,
    'The invitation smells faintly of biscuits. Basil owns the moonlit mews, or at least insists he does. The two courtyards offer separate places to build, until the narrow crossing brings you together.',
    'Basil hands over a brass key and the last biscuit. Both are surprisingly good investments.',
    'Watch which chain will survive before joining the courtyards.'],
  ['The breakfast exchange', 'Market Square', 'four-market-square', 3,
    'Two regulars have turned the breakfast market into a private stock exchange. Moxie talks fast; Vera barely talks at all. You need to beat both before they will put your name on the proper guest list.',
    'Your name goes on the list. Someone has underlined it twice in marmalade.',
    'Three investors make majority contests harder. Count the shares before spending.'],
  ['Lanterns after dark', 'The lantern quarter', 'four-paper-lantern', 3,
    'The next table opens when the lanterns come on. Otto has sworn off reckless spending, and Cleo can hear a merger three streets away. Climb the narrow city without handing either of them the evening bonus.',
    'One lantern stays lit in your honor. The invitation beneath it carries the old boardroom seal.',
    'Keep enough cash to buy after a merger opens the bank again.'],
  ['The old boardroom', 'The original city', 'classic', 4,
    'At last, the original 12×9 city. Percy, Nora and Gus have kept this table for years. They will happily explain their favorite moves after they have used them against you.',
    'Three old regulars raise their cups. You have earned your first seat at the city council.',
    'Growing a hotel is most valuable when its shares work for you.'],
  ['The infinity clause', 'Jade waterfront', 'jade-infinity', 4,
    'A curious clause in the ledger points to two looping waterfronts. Dot knows every bonus, Felix loves a contested majority, and Tilda collects shares like porcelain. There are two routes forward and no easy opponents.',
    'The loops are closed, the ledger balances, and an elevator key falls from the next page.',
    'The best merger is the one whose payout improves your position against the table.'],
  ['Above the clouds', 'The sky palaces', 'cloud-palace', 6,
    'The elevator stops above the clouds. Five eccentric owners greet you from four floating palaces. Below, the city looks small. At this table, every founding share has five people watching it.',
    'Your skyline reaches the clouds. A silver moth lands on a letter addressed to you.',
    'A small minority holding can matter when several investors contest the same chain.'],
  ['A wing and a share', 'The moonlit conservatory', 'lunar-moth', 6,
    'The conservatory hosts a midnight auction. Five new rivals gather beneath enormous moth-shaped wings. The central body links every district, and everyone has a different idea about when to cross it.',
    'The auctioneer rings the bell. Your next invitation is stamped with a very large dragon.',
    'Narrow crossings make the contents of your rack especially valuable.'],
  ['Here be landlords', 'Dragon Spine', 'big-dragon-spine', 8,
    'The dragon district stretches farther than the old ledger can fold. Seven landlords have gathered along its ribs and crests. They agree on almost nothing, except that you have arrived a little too confidently.',
    'Seven signatures certify your place among the great builders. One is just an impressive ink blot.',
    'With eight investors, follow the largest rival payout as closely as your own.'],
  ['The midnight society', 'Moon Mosaic', 'big-moon-mosaic', 8,
    'Five moon courts hide a table belonging to a very peculiar society. The dress code is formal; the tactics are not. Seven strangers offer you a chair and absolutely no useful advice.',
    'They make you an honorary member. Your badge is a tiny umbrella for your portfolio.',
    'Protect a bonus lead when the bank is running low on certificates.'],
  ['A storm of suits', 'Thunderbird heights', 'mega-thunderbird', 10,
    'Thunder rolls through the feathered skyline. Nine rivals arrive with umbrellas, clipboards and implausible hats. The final invitation is on this table. To take it, you must finish above every one of them.',
    'The storm clears. Behind the clouds stands the World Tree, and eleven empty chairs await their owners.',
    'A safe chain can still grow. Balance its final value against cash you need now.'],
  ['The city is yours', 'The World Tree summit', 'max-world-tree', 12,
    'Your battered ledger opens to the last page of its first chapter. Eleven legendary investors take their places among the roots and canopies of the biggest city. No favors, no easy seats: win the summit and write your own ending.',
    'Grandpa Goldleaf closes the ledger, then gives it back. There is a new page inside. The city is yours—and the next story is yours to build.',
    'Watch the end conditions. Winning the table means knowing when to ring the closing bell.'],
];
export const STORY_BOOKS = [
  { number: 1, title: 'The first ledger', theme: 'Learn the city, from a corner café to the World Tree.' },
  { number: 2, title: 'Small city, sharp elbows', theme: 'Thirteen duels in tight economies. Every certificate matters.' },
  { number: 3, title: 'The neighborhood exchange', theme: 'Four-way contests introduce market timing and faster construction.' },
  { number: 4, title: 'The restless skyline', theme: 'Six-seat cities combine dividends, tactical demolition and reinvestment.' },
  { number: 5, title: 'The great guilds', theme: 'Eight investors compete over uneven supplies and changing price windows.' },
  { number: 6, title: 'The midnight syndicate', theme: 'Ten-seat tables test discretion, liquidity and volatile markets.' },
  { number: 7, title: 'The golden succession', theme: 'Twelve-seat megacities lead to the royal crown and its final eleven rivals.' },
] as const;
const strategies = [
  'Scarcity makes bonus leads harder to dislodge. Keep a cash reserve rather than buying every available certificate.',
  'Buy when the market is low, then weigh selling high against surrendering a bonus position. A cheap trade can finance a stronger bid.',
  'Several placements can form, grow and merge a chain in one turn. Use your rack as a sequence, and stop early if another placement helps a rival.',
  'Dividends reward holdings while chains are still alive. Interior tiles may return to the bag, so watch the shape as well as the share count.',
  'Removing a legal edge can change tomorrow’s connection. Removal must leave at least two connected tiles in a chain.',
  'Slow market windows reward preparation. Per-turn windows reward flexibility. Final sales roll a separate market for every active chain.',
];
function challengeStrategy(chapter: number, stage: number, rules: Partial<HouseRules>): string {
  const lane = (stage - 1) % 6;
  if (chapter === 2) return [
    'In a duel, a single certificate can win both bonuses. Use the small supply to secure a lead without spending your entire reserve.',
    'Turn sales open extra purchase slots. Reinvest only when the new bonus position is worth losing your old certificates.',
    'Study the crossings in your rack: a cheap founding can become a cash windfall, but growing a rival’s chain can lock out that merger.',
    'There are few chains and few tiles. Balance the price of the last certificate against keeping cash for the next founding.',
    'Keeping acquired shares can save a future rebuy. Check whether your remaining rack can actually found that hotel again.',
    'Plan the closing bell before your opponent does. An early all-safe ending may secure a narrow lead.',
  ][lane];
  if (lane === 3 && !rules.dividends) return 'The market changes before each investor’s turn. Multi-tile construction can create a merger before a rival gets another price window.';
  if (lane === 4 && !rules.removalsPerTurn) return 'Sales can fund several purchases in one turn. Protect your bonus lead while using the next market window to build another position.';
  return strategies[lane];
}
/** Authored progression: mechanics are introduced before they are combined. */
function challengeRules(chapter: number, stage: number): Partial<HouseRules> {
  const lane = (stage - 1) % 6;
  const rosterCount = chapter === 2 ? 3 + stage % 3 : Math.min(12, chapter + 3 + stage % 3);
  const roster = CHAIN_IDS.filter((_, index) => (index + stage) % 12 < rosterCount);
  const supply = chapter < 5 ? 12 + stage % 7 * 2 : 24 + stage % 7 * 3;
  return {
    hotelChains: roster,
    shareSupply: Object.fromEntries(roster.map((chain, i) => [chain, supply + (i % 3) * 3])),
    startingCash: (chapter === 2 ? 3500 : chapter === 3 ? 4500 : 6000) + (stage % 4) * 500,
    startingTilesPerPlayer: chapter >= 3 && lane >= 3 ? 2 : 1,
    buyLimit: chapter === 2 ? 1 + stage % 2 : 2 + stage % 3,
    trading: lane === 1 || lane >= 4 || chapter >= 5,
    placementsPerTurn: chapter >= 3 && lane >= 2 ? (chapter >= 5 && lane === 5 ? 3 : 2) : 1,
    removalsPerTurn: chapter >= 4 && lane >= 4 ? 1 : 0,
    dividends: chapter >= 4 && lane !== 1,
    marketMode: chapter === 2 ? 'off' : chapter >= 5 && lane >= 3 ? 'crazy' : lane === 0 ? 'off' : 'market',
    marketFrequency: ['three-rounds', 'two-rounds', 'round', 'turn', 'two-rounds', 'turn'][lane] as HouseRules['marketFrequency'],
    hiddenMoney: chapter >= 6 && lane === 3,
    anonymousBuying: chapter >= 6 && lane === 4,
  };
}
let offset = 0;
const firstChapter = chapters.map(([title, district, mapId, players, intro, victory, tip], index): StoryChapter => {
  const opponents = CHARACTERS.slice(offset, offset + players - 1).map((character) => character.id);
  offset += players - 1;
  return { id: `chapter-${index + 1}`, number: index + 1, chapter: 1, stage: index + 1, title, district, mapId, players, intro, victory, tip, opponents, strategy: tip, houseRules: {} };
});
const used = new Set(firstChapter.map((item) => item.mapId));
const laterChapters: StoryChapter[] = [];
for (const [index, seats] of [2, 4, 6, 8, 10, 12].entries()) {
  const chapter = index + 2;
  const maps = MAPS.filter((map) => map.maxPlayers === seats && !used.has(map.id) && map.id !== 'goldspire-kingdom');
  maps.forEach((map, i) => {
    const stage = i + 1, houseRules = challengeRules(chapter, stage), strategy = challengeStrategy(chapter, stage, houseRules);
    const opponents = CHARACTERS.slice(offset, offset + seats - 1).map((character) => character.id);
    offset += seats - 1;
    laterChapters.push({ id: `story-${map.id}`, number: firstChapter.length + laterChapters.length + 1,
      chapter, stage, title: map.name, district: map.palette.name, mapId: map.id, players: seats,
      intro: `The ledger opens onto ${map.name}. ${map.description} A new circle of ${seats - 1} rivals has written its own terms into the margins. ${STORY_BOOKS[chapter - 1].theme}`,
      victory: `Your signature joins the skyline of ${map.name}. The next page carries a fresh invitation and a different set of terms.`,
      tip: strategy, strategy, opponents, houseRules,
    });
  });
}
const royalRules: Partial<HouseRules> = {
  hotelChains: [...CHAIN_IDS], shareSupply: Object.fromEntries(CHAIN_IDS.map((chain) => [chain, 36])),
  startingCash: 8000, startingTilesPerPlayer: 2, placementsPerTurn: 3, removalsPerTurn: 1,
  buyLimit: 4, trading: true, dividends: true, marketMode: 'crazy', marketFrequency: 'turn',
};
/** IDs of the original twelve stay unchanged, preserving existing progress and saves. */
export const STORY_CHAPTERS: readonly StoryChapter[] = [...firstChapter, ...laterChapters, {
  id: 'story-goldspire-kingdom', number: 81, chapter: 7, stage: 7,
  title: 'Goldspire Kingdom', district: 'The royal succession', mapId: 'goldspire-kingdom', players: 12,
  intro: 'Every road in your ledger leads here: five golden spires, eleven sovereigns and one vacant throne. Put on your crown. These kings and queens will make you earn the kingdom.',
  victory: 'Eleven crowns bow. Goldspire Kingdom and its royal rivals are now yours to invite into free play.',
  tip: 'Treat each turn as a three-tile plan. Protect liquidity through volatile prices, and trade into a survivor only when its bonus prospects justify it.',
  strategy: 'All twelve chains, deeper certificate supplies, dividends, demolition and a fresh market before every turn. Your strongest weapon is choosing when to build, sell, trade and finally close the kingdom.',
  opponents: ROYAL_CHARACTERS.map((character) => character.id), houseRules: royalRules,
}];
export const getStoryChapter = (id?: string) => STORY_CHAPTERS.find((chapter) => chapter.id === id);
export function storyGameConfig(chapterId: string, name: string, seed: number, avatar?: string): GameConfig {
  const chapter = getStoryChapter(chapterId);
  if (!chapter) throw new Error('Choose a challenge from The Long Game.');
  const playerId = 'story-player', royal = chapter.mapId === 'goldspire-kingdom';
  return {
    id: `story-${chapter.number}-${seed.toString(36)}-${Date.now().toString(36)}`,
    seed, mapId: chapter.mapId, mode: 'classic', botDifficulty: 'strategist',
    campaign: { version: 1, chapterId, playerId }, houseRules: chapter.houseRules,
    players: [{ id: playerId, name: royal ? `${/^(King|Queen) /.test(name) ? '' : 'King '}${name.trim() || 'You'}`.slice(0, 30) : name.trim() || 'You',
      isBot: false, avatar: royal ? royalAvatar(avatar) : avatar }, ...chapter.opponents.map((id) => {
      const character = CHARACTERS.find((candidate) => candidate.id === id)!;
      return { id: `story-${id}`, name: character.name, isBot: true, characterId: id };
    })],
  };
}
export function storyRuleBriefing(challenge: StoryChapter): { title: string; detail: string }[] {
  const rules = validateHouseRules(challenge.houseRules), map = getMap(challenge.mapId);
  const names = rules.hotelChains.map((id) => CHAINS.find((chain) => chain.id === id)!.name);
  const frequency = { round: 'after each complete round', turn: 'before each player’s turn', 'two-rounds': 'after every two rounds', 'three-rounds': 'after every three rounds' };
  return [
    { title: 'City and end conditions', detail: `${challenge.players} players · ${map.tiles.length} tiles. After playing, you may declare the end at ${map.endSize} tiles in one chain, or when all active chains are safe. Inactive chains do not count. If no remaining rack or draw tile can be played or reopened by a removal, the exhausted table settles automatically.` },
    { title: 'Hotel roster and certificates', detail: names.map((name, i) => `${name}: ${rules.shareSupply[rules.hotelChains[i]] ?? 25} shares`).join(' · ') + '. Only these hotels can be founded.' },
    { title: 'Opening and cash', detail: `${rules.startingCash.toLocaleString('en-US')} dollars each; ${rules.startingTilesPerPlayer} starting tile${rules.startingTilesPerPlayer === 1 ? '' : 's'} per player. Adjacent setup tiles remain independent. Everyone receives a six-tile rack.` },
    { title: 'Construction and demolition', detail: `Place up to ${rules.placementsPerTurn} tile${rules.placementsPerTurn === 1 ? '' : 's'} per turn. ${rules.removalsPerTurn ? `Remove up to ${rules.removalsPerTurn} legal tile; it returns to the bag. A chain must retain at least two connected tiles.` : 'Tile removal is off.'} Refill your rack after investing.` },
    { title: 'Buying and selling', detail: `Buy up to ${rules.buyLimit} shares. ${rules.trading ? 'Sell up to three shares at current prices, earning one extra purchase per share sold. Reinvest in the same turn.' : 'Ordinary stock selling is off; merger sales and trades still apply.'}` },
    { title: 'Market prices', detail: rules.marketMode === 'off' ? 'Printed prices; no market rolls.' : `${rules.marketMode === 'crazy' ? 'Crazy market moves prices by up to two rows' : 'Market moves prices by up to one row'} ${frequency[rules.marketFrequency]}. Buying, selling, bonuses and dividends use that market. Every active chain rolls separately at final sale.` },
    { title: 'Dividends', detail: rules.dividends ? 'After every round, dice select only an active chain. Complete price-tier groups of active hotels determine the dividend success chance. A successful roll pays one share price per three shares held; tiles surrounded on all eight sides by that chain return to the bag. No active chain means no selection or payment.' : 'Round-end dividends are off.' },
    { title: 'Information and time', detail: `${rules.anonymousBuying ? 'Other players’ purchases, holdings, bank counts and cash stay private until final scoring; merger quantities are announced privately.' : rules.hiddenMoney ? 'Other players’ cash is hidden; stock decisions remain public.' : 'Public cash and market decisions. Your rack always stays private.'} No turn timer: take time to plan. CPUs use the same information rules.` },
    { title: 'Merger and rack rules', detail: '11+ tiles makes a chain safe. Two safe chains cannot merge. Merger bonuses pay first, then shareholders decide clockwise from the mover: sell, trade two acquired shares for one survivor share, or keep. Permanently blocked tiles may be retired. At the beginning of a turn, an entirely unplayable six-tile rack may be exchanged, including temporary blocks.' },
  ];
}
