// Generated by supabase/sync-engine.mjs. Edit src/game/engine.ts.
import {
  CHAIN_IDS,
  DEFAULT_CHAIN_IDS,
  type ChainDefinition,
  type ChainId,
  type GameAction,
  type GameConfig,
  type GameLog,
  type GameMode,
  type GameState,
  type HouseRules,
  type PlayerMetrics,
  type PlayerAward,
  type Player,
  type Stocks,
  type Tile,
  type TileAnalysis,
} from './types.ts';
import { getMap, isMapId, mapHasTile } from './maps.ts';
export * from './types.ts';
export { MAPS, getMap } from './maps.ts';

/** Rules: Avalon Hill / Wizards of the Coast Acquire, ©1999, 2008. */
export const RULEBOOK_URL = 'https://media.wizards.com/2015/downloads/ah/acquire_rules.pdf';
export const CHAINS: ChainDefinition[] = [
  {
    id: 'budgeton', name: 'Budgeton', tier: -1,
    color: '#8b5b45', light: '#f2e4d9', abbreviation: 'BU',
    description: 'Value starts here.',
  },
  {
    id: 'worldwide',
    name: 'Worldwide',
    tier: 0,
    color: '#9b78ad',
    light: '#eee1f3',
    abbreviation: 'WW',
    description: 'Think beyond borders.',
  },
  {
    id: 'sackson',
    name: 'Sackson',
    tier: 0,
    color: '#e56845',
    light: '#fae1d7',
    abbreviation: 'SA',
    description: 'A bold beginning.',
  },
  {
    id: 'heritage', name: 'Heritage', tier: 0,
    color: '#69813a', light: '#e8eedb', abbreviation: 'HE',
    description: 'A legacy worth keeping.',
  },
  {
    id: 'festival',
    name: 'Festival',
    tier: 1,
    color: '#4b947b',
    light: '#dcefe5',
    abbreviation: 'FE',
    description: 'A welcoming investment.',
  },
  {
    id: 'imperial',
    name: 'Imperial',
    tier: 1,
    color: '#dba92d',
    light: '#faedc8',
    abbreviation: 'IM',
    description: 'The height of hospitality.',
  },
  {
    id: 'american',
    name: 'American',
    tier: 1,
    color: '#4878b6',
    light: '#dce8f6',
    abbreviation: 'AM',
    description: 'Room to grow.',
  },
  {
    id: 'riviera', name: 'Riviera', tier: 1,
    color: '#168b9a', light: '#dcf2f4', abbreviation: 'RI',
    description: 'The coast is calling.',
  },
  {
    id: 'continental',
    name: 'Continental',
    tier: 2,
    color: '#c94c45',
    light: '#f8dfdc',
    abbreviation: 'CO',
    description: 'A world of possibility.',
  },
  {
    id: 'tower',
    name: 'Tower',
    tier: 2,
    color: '#687078',
    light: '#e4e7e9',
    abbreviation: 'TO',
    description: 'Built to rise.',
  },
  {
    id: 'monarch', name: 'Monarch', tier: 2,
    color: '#414c99', light: '#e3e6f6', abbreviation: 'MO',
    description: 'A royal place to stay.',
  },
  {
    id: 'goldspire', name: 'Goldspire', tier: 3,
    color: '#a47613', light: '#f5ebcc', abbreviation: 'GO',
    description: 'The highest address.',
  },
];
export const ALL_TILES: Tile[] = Array.from(
  { length: 108 },
  (_, i) => `${(i % 12) + 1}${String.fromCharCode(65 + Math.floor(i / 12))}`,
);
const DEFINITIONS = Object.fromEntries(CHAINS.map((chain) => [chain.id, chain])) as Record<
  ChainId,
  ChainDefinition
>;
export const DEFAULT_HOUSE_RULES: HouseRules = {
  hotelChains: [...DEFAULT_CHAIN_IDS],
  shareSupply: {},
  startingTilesPerPlayer: 1,
  startingCash: 6000,
  placementsPerTurn: 1,
  removalsPerTurn: 0,
  turnTimerSeconds: 0,
  hiddenMoney: false,
  anonymousBuying: false,
  buyLimit: 3,
  dividends: false,
  trading: false,
  marketMode: 'off',
  marketFrequency: 'round',
};
export const getHouseRules = (source?: GameState | Partial<HouseRules>): HouseRules => {
  const chosen = source && 'players' in source ? source.houseRules : source;
  return {
    ...DEFAULT_HOUSE_RULES, ...chosen,
    hotelChains: chosen?.hotelChains ?? DEFAULT_HOUSE_RULES.hotelChains,
    shareSupply: chosen?.shareSupply ?? DEFAULT_HOUSE_RULES.shareSupply,
  };
};
export function validateHouseRules(input?: Partial<HouseRules>): HouseRules {
  assert(!input || (typeof input === 'object' && !Array.isArray(input) && Object.keys(input).every((key) => key in DEFAULT_HOUSE_RULES)),
    'Choose valid house-rule settings.');
  const rules = getHouseRules(input);
  assert(Array.isArray(rules.hotelChains) && rules.hotelChains.length >= 2 && rules.hotelChains.length <= CHAIN_IDS.length
    && rules.hotelChains.every((chain) => validChain(chain))
    && new Set(rules.hotelChains).size === rules.hotelChains.length,
  'Choose at least two different hotels from the available roster.');
  rules.hotelChains = CHAIN_IDS.filter((chain) => rules.hotelChains.includes(chain));
  const integer = (value: number, min: number, max: number) => Number.isInteger(value) && value >= min && value <= max;
  assert(rules.shareSupply && typeof rules.shareSupply === 'object' && !Array.isArray(rules.shareSupply)
    && Object.entries(rules.shareSupply).every(([chain, count]) => validChain(chain) && integer(count, 1, 100)),
  'Hotel share supplies must be whole numbers from 1 to 100.');
  rules.shareSupply = Object.fromEntries(Object.entries(rules.shareSupply).filter(([, count]) => count !== 25)) as Partial<Stocks>;
  assert(integer(rules.startingTilesPerPlayer, 1, 10), 'Starting tiles must be between one and ten per player.');
  assert(integer(rules.startingCash, 0, 1000000), 'Starting cash must be between $0 and $1,000,000.');
  assert(integer(rules.placementsPerTurn, 1, 6), 'Place between one and six tiles per turn.');
  assert(integer(rules.removalsPerTurn, 0, Math.min(5, rules.placementsPerTurn - 1)), 'Removed tiles must be fewer than placed tiles, with a maximum of five.');
  assert(rules.turnTimerSeconds === 0 || integer(rules.turnTimerSeconds, 5, 600), 'The turn timer must be off or between five seconds and ten minutes.');
  assert(integer(rules.buyLimit, 1, 10), 'The share purchase limit must be between one and ten.');
  assert(['off', 'market', 'crazy'].includes(rules.marketMode), 'Choose an available market mode.');
  assert(['round', 'turn', 'two-rounds', 'three-rounds'].includes(rules.marketFrequency), 'Choose an available market roll frequency.');
  assert(['hiddenMoney', 'anonymousBuying', 'dividends', 'trading'].every((key) => typeof rules[key as keyof HouseRules] === 'boolean'), 'Choose valid house-rule switches.');
  return rules;
}
const stockMap = (value: number): Stocks =>
  Object.fromEntries(CHAIN_IDS.map((id) => [id, value])) as Stocks;
const money = (amount: number) => `$${amount.toLocaleString('en-US')}`;
const roundHundred = (amount: number) => Math.ceil(amount / 100) * 100;
function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}
const validChain = (chain: unknown): chain is ChainId => CHAIN_IDS.includes(chain as ChainId);
export const getHotelChains = (state: GameState): ChainId[] => getHouseRules(state).hotelChains;
const nextRandom = (state: Pick<GameState, 'rng'>): number => {
  state.rng = (state.rng + 0x6d2b79f5) >>> 0;
  let t = state.rng;
  t = Math.imul(t ^ (t >>> 15), t | 1);
  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
function shuffle(state: Pick<GameState, 'rng'>, tiles: Tile[]) {
  for (let i = tiles.length - 1; i > 0; i--) {
    const j = Math.floor(nextRandom(state) * (i + 1));
    [tiles[i], tiles[j]] = [tiles[j], tiles[i]];
  }
}
function log(
  state: GameState,
  type: GameLog['type'],
  message: string,
  extra: Partial<GameLog> = {},
) {
  state.logSequence = (state.logSequence ?? state.logs.at(-1)?.id ?? 0) + 1;
  state.logs.push({ id: state.logSequence, turn: state.turn, type, message, ...extra });
  if (state.logs.length > 512) state.logs.splice(0, state.logs.length - 512);
}
const emptyMetrics = (): PlayerMetrics => ({
  tilesPlaced: 0, mergesCaused: 0, chainsFounded: 0, sharesBought: 0,
  mergerBonuses: 0, sharesSold: 0, cashSpent: 0,
});
const metric = (state: GameState, id: string): PlayerMetrics => {
  state.metrics ??= {};
  return (state.metrics[id] ??= emptyMetrics());
};
export function tileCoordinates(tile: Tile): { column: number; row: number } {
  assert(/^[1-9]\d?[A-Z]$/.test(tile), 'That building tile is not on this board.');
  return { column: parseInt(tile, 10) - 1, row: tile.charCodeAt(tile.length - 1) - 65 };
}
export function getNeighbors(tile: Tile, mapId?: GameState['mapId']): Tile[] {
  const { column, row } = tileCoordinates(tile);
  const map = getMap(mapId);
  return [
    [column - 1, row],
    [column + 1, row],
    [column, row - 1],
    [column, row + 1],
  ]
    .filter(([c, r]) => c >= 0 && c < map.columns && r >= 0 && r < map.rows)
    .map(([c, r]) => `${c + 1}${String.fromCharCode(65 + r)}`);
}
export function getChainSize(state: GameState, chain: ChainId): number {
  return Object.values(state.board).filter((value) => value === chain).length;
}
export function getAvailableChains(state: GameState): ChainId[] {
  return getHotelChains(state).filter((chain) => getChainSize(state, chain) === 0);
}
export function getActiveChains(state: GameState): ChainId[] {
  return getHotelChains(state).filter((chain) => getChainSize(state, chain) > 0);
}
/** An inactive chain is worth zero. During a merger use its stored original size for selling. */
export function getSharePrice(state: GameState, chain: ChainId): number {
  return getMarketPriceForSize(state, chain, getChainSize(state, chain));
}
export function getMarketPriceForSize(state: GameState, chain: ChainId, size: number, shift = state.marketShift ?? 0): number {
  if (size < 2) return 0;
  const rows = [200, 300, 400, 500, 600, 700, 800, 900, 1000];
  const row = size <= 5 ? size - 2 : size <= 10 ? 4 : size <= 20 ? 5 : size <= 30 ? 6 : size <= 40 ? 7 : 8;
  return rows[Math.max(0, Math.min(8, row + shift))] + DEFINITIONS[chain].tier * 100;
}
export function getPriceForSize(chain: ChainId, size: number): number {
  if (size < 2) return 0;
  const base =
    size <= 5
      ? size * 100
      : size <= 10
        ? 600
        : size <= 20
          ? 700
          : size <= 30
            ? 800
            : size <= 40
              ? 900
              : 1000;
  return base + DEFINITIONS[chain].tier * 100;
}
export function getBonusAmounts(price: number, mode: GameMode = 'classic'): number[] {
  assert(mode === 'classic', 'The 2008 edition uses majority and minority bonuses.');
  return price <= 0 ? [0, 0] : [price * 10, price * 5];
}
/** Entries correspond to the supplied player holdings. Zero-share players never qualify. */
export function calculateBonuses(
  holdings: number[],
  price: number,
  mode: GameMode = 'classic',
): number[] {
  const payout = holdings.map(() => 0);
  const levels = [...new Set(holdings.filter((n) => n > 0))].sort((a, b) => b - a);
  if (levels.length === 0) return payout;
  const groups = levels.map((level) => holdings.flatMap((n, i) => (n === level ? [i] : [])));
  const [primary, secondary] = getBonusAmounts(price, mode);
  const assign = (group: number[] | undefined, total: number) => {
    if (group?.length) for (const i of group) payout[i] += roundHundred(total / group.length);
  };
  const holders = holdings.filter((n) => n > 0).length;
  if (holders === 1) {
    assign(groups[0], primary + secondary);
    return payout;
  }
  if (groups[0].length > 1) assign(groups[0], primary + secondary);
  else {
    assign(groups[0], primary);
    assign(groups[1], secondary);
  }
  return payout;
}
export function getCurrentActor(state: GameState): Player {
  if (state.phase === 'merger-shares' && state.merger)
    return state.players[state.merger.shareholders[state.merger.shareholderCursor]];
  return state.players[state.currentPlayer];
}
export function getNetWorth(state: GameState, playerOrId: Player | string | number): number {
  const player =
    typeof playerOrId === 'number'
      ? state.players[playerOrId]
      : typeof playerOrId === 'string'
        ? state.players.find((p) => p.id === playerOrId)
        : playerOrId;
  assert(player, 'Player was not found.');
  return (
    player.cash +
    getHotelChains(state).reduce(
      (total, chain) => total + (player.stocks[chain] ?? 0) * getSharePrice(state, chain),
      0,
    )
  );
}
function independentConnection(state: GameState, tile: Tile): { tiles: Tile[]; chains: ChainId[] } {
  const tiles = new Set<Tile>([tile]);
  const chains = new Set<ChainId>();
  const queue = [tile];
  while (queue.length) {
    const item = queue.shift()!;
    for (const neighbor of getNeighbors(item, state.mapId)) {
      const value = state.board[neighbor];
      if (value === 'independent' && !tiles.has(neighbor)) {
        tiles.add(neighbor);
        queue.push(neighbor);
      } else if (value && value !== 'independent') chains.add(value);
    }
  }
  return { tiles: [...tiles], chains: getHotelChains(state).filter((chain) => chains.has(chain)) };
}
export function analyzeTile(state: GameState, tile: Tile): TileAnalysis {
  if (!mapHasTile(state.mapId, tile) || state.board[tile] || state.discarded.includes(tile))
    return {
      tile,
      legal: false,
      kind: 'unavailable',
      chains: [],
      connectedTiles: [],
      reason: 'This tile is not available.',
      permanent: false,
    };
  const { tiles, chains } = independentConnection(state, tile);
  const safe = chains.filter((chain) => getChainSize(state, chain) >= 11);
  if (safe.length > 1)
    return {
      tile,
      legal: false,
      kind: 'blocked',
      chains,
      connectedTiles: tiles,
      reason:
        'Two safe chains cannot merge. Reveal and replace this permanently unplayable tile.',
      permanent: true,
    };
  if (chains.length > 1)
    return {
      tile,
      legal: true,
      kind: 'merge',
      chains,
      connectedTiles: tiles,
      reason: null,
      permanent: false,
    };
  if (chains.length === 1)
    return {
      tile,
      legal: true,
      kind: 'grow',
      chains,
      connectedTiles: tiles,
      reason: null,
      permanent: false,
    };
  if (tiles.length > 1) {
    const legal = getAvailableChains(state).length > 0;
    return {
      tile,
      legal,
      kind: legal ? 'found' : 'blocked',
      chains,
      connectedTiles: tiles,
      reason: legal
        ? null
        : `All ${getHotelChains(state).length} chains are active. This tile must wait until a chain is acquired.`,
      permanent: false,
    };
  }
  return {
    tile,
    legal: true,
    kind: 'independent',
    chains,
    connectedTiles: tiles,
    reason: null,
    permanent: false,
  };
}
export function getLegalTiles(state: GameState, playerId?: string): Tile[] {
  const player = playerId
    ? state.players.find((p) => p.id === playerId)
    : state.players[state.currentPlayer];
  return player ? player.hand.filter((tile) => analyzeTile(state, tile).legal) : [];
}
export function canRemoveTile(state: GameState, tile: Tile): boolean {
  const value = state.board[tile];
  if (!value || !mapHasTile(state.mapId, tile)) return false;
  if (state.logs.some((entry) => entry.turn === state.turn && entry.type === 'tile' && entry.tile === tile)) return false;
  if (value === 'independent') return true;
  const remaining = Object.keys(state.board).filter((coordinate) => coordinate !== tile && state.board[coordinate] === value);
  if (remaining.length < 2) return false;
  const visited = new Set<Tile>([remaining[0]]);
  const queue = [remaining[0]];
  while (queue.length) {
    for (const neighbor of getNeighbors(queue.pop()!, state.mapId)) {
      if (state.board[neighbor] === value && neighbor !== tile && !visited.has(neighbor)) {
        visited.add(neighbor);
        queue.push(neighbor);
      }
    }
  }
  return visited.size === remaining.length;
}
export function getRemovableTiles(state: GameState): Tile[] {
  if (state.phase !== 'place' || (state.removalsThisTurn ?? 0) >= getHouseRules(state).removalsPerTurn) return [];
  return Object.keys(state.board).filter((tile) => canRemoveTile(state, tile));
}
export function endConditionMet(state: GameState): boolean {
  const map = getMap(state.mapId);
  const sizes = getActiveChains(state).map((chain) => getChainSize(state, chain));
  return (
    sizes.some((size) => size >= map.endSize) ||
    (sizes.length > 0 && sizes.every((size) => size >= 11))
  );
}
export function canEndGame(state: GameState): boolean {
  return state.tilePlacedThisTurn && state.phase === 'buy' && !state.merger && endConditionMet(state);
}
export function createGame(config: GameConfig): GameState {
  assert(isMapId(config?.mapId ?? 'classic'), 'Choose an available city map.');
  const map = getMap(config?.mapId);
  assert(
    config &&
      Array.isArray(config.players) &&
      config.players.length >= 3 &&
      config.players.length <= map.maxPlayers,
    map.maxPlayers === 6
      ? 'Choose between three and six players for the 2008 edition.'
      : `Choose between three and ${map.maxPlayers} players for this custom map.`,
  );
  assert(
    config.players.every(
      (p) =>
        typeof p.id === 'string' &&
        p.id.length > 0 &&
        typeof p.name === 'string' &&
        p.name.trim().length > 0,
    ),
    'Every player needs a name and unique ID.',
  );
  assert(
    new Set(config.players.map((p) => p.id)).size === config.players.length,
    'Player IDs must be unique.',
  );
  assert(
    config.mode === undefined || config.mode === 'classic',
    'The 2008 edition uses Classic rules only.',
  );
  assert(['casual', 'standard', 'strategist'].includes(config.botDifficulty ?? 'standard'), 'Choose an available computer difficulty.');
  const houseRules = validateHouseRules(config.houseRules);
  assert(config.players.length * (houseRules.startingTilesPerPlayer + 6) <= map.tiles.length,
    `This map needs at least ${config.players.length * (houseRules.startingTilesPerPlayer + 6)} tiles for that opening and six-tile racks. Choose fewer starting tiles or a larger map.`);
  const seed = (config.seed ?? Date.now()) >>> 0;
  const state: GameState = {
    version: 2,
    ruleset: '2008',
    id: config.id ?? `aquire-${seed.toString(36)}`,
    mode: 'classic',
    mapId: config.mapId ?? 'classic',
    botDifficulty: config.botDifficulty ?? 'standard',
    houseRules,
    placementsThisTurn: 0,
    removalsThisTurn: 0,
    turnDeadlineAt: houseRules.turnTimerSeconds ? Date.now() + houseRules.turnTimerSeconds * 1000 : null,
    marketShift: 0,
    seed,
    rng: seed,
    revision: 0,
    turn: 1,
    phase: 'place',
    currentPlayer: 0,
    players: [],
    board: {},
    bank: { ...stockMap(25), ...houseRules.shareSupply },
    bag: [...map.tiles],
    discarded: [],
    logs: [],
    logSequence: 0,
    metrics: {},
    finalSettlements: [],
    awards: [],
    lastPlacedTile: null,
    tilePlacedThisTurn: false,
    foundingTiles: [],
    merger: null,
    endDeclared: false,
    endReason: null,
    results: [],
    winnerIds: [],
  };
  shuffle(state, state.bag);
  state.players = config.players.map((p) => {
    const initialTile = state.bag.pop()!;
    state.board[initialTile] = 'independent';
    return {
      id: p.id,
      name: p.name.trim().slice(0, 30),
      isBot: Boolean(p.isBot),
      cash: houseRules.startingCash,
      stocks: stockMap(0),
      hand: [],
      initialTile,
    };
  });
  for (const player of state.players) state.metrics![player.id] = emptyMetrics();
  const position = (tile: Tile) => {
    const c = tileCoordinates(tile);
    return c.row * map.columns + c.column;
  };
  state.currentPlayer = state.players.reduce(
    (best, p, index) =>
      position(p.initialTile) < position(state.players[best].initialTile) ? index : best,
    0,
  );
  for (let extra = 1; extra < houseRules.startingTilesPerPlayer; extra++) {
    for (const player of state.players) {
      const coordinate = state.bag.pop()!;
      state.board[coordinate] = 'independent';
      log(state, 'setup', `${player.name} adds ${coordinate} to the opening city.`, { playerId: player.id, tile: coordinate });
    }
  }
  for (const player of state.players)
    for (let i = 0; i < 6; i++) player.hand.push(state.bag.pop()!);
  log(
    state,
    'setup',
    `${map.maxPlayers > 6 ? 'Custom expansion map with 2008 prices and shareholder rules.' : '2008 edition.'} Each investor begins with ${money(houseRules.startingCash)} and six private building tiles.`,
  );
  for (const p of state.players)
    log(state, 'setup', `${p.name} drew ${p.initialTile} for seating.`, {
      playerId: p.id,
      tile: p.initialTile,
    });
  log(
    state,
    'turn',
    `${state.players[state.currentPlayer].name} goes first with the tile closest to 1A.`,
    { playerId: state.players[state.currentPlayer].id },
  );
  if (houseRules.marketMode !== 'off' && houseRules.marketFrequency === 'turn') {
    settleDice(state, false, true, true);
    if (houseRules.turnTimerSeconds)
      state.turnDeadlineAt = Date.now() + houseRules.turnTimerSeconds * 1000 + DICE_REVEAL_GRACE_MS;
  }
  return state;
}
function payBonuses(state: GameState, chain: ChainId, size: number, price = getMarketPriceForSize(state, chain, size)): number[] {
  const holdings = state.players.map((player) => player.stocks[chain]);
  const payouts = calculateBonuses(holdings, price, state.mode);
  state.players.forEach((player, index) => {
    if (payouts[index]) {
      player.cash += payouts[index];
      if (state.phase !== 'ended' && state.merger) metric(state, player.id).mergerBonuses += payouts[index];
      log(
        state,
        'bonus',
        `${player.name} receives ${money(payouts[index])} in ${DEFINITIONS[chain].name} shareholder bonuses.`,
        { playerId: player.id, chain },
      );
    }
  });
  return payouts.slice(0, state.players.length);
}
export function makeAwards(state: GameState): PlayerAward[] {
  const awards: PlayerAward[] = [];
  const add = (id: string, title: string, detail: string, icon: PlayerAward['icon']) =>
    awards.push({ playerId: id, title, detail, icon });
  for (const id of state.winnerIds) add(id, 'City Champion', 'Finished with the highest fortune', 'crown');
  const categories: [keyof PlayerMetrics, string, string, PlayerAward['icon']][] = [
    ['mergesCaused', 'Deal Maker', 'Most mergers set in motion', 'merge'],
    ['chainsFounded', 'Founder', 'Most hotel chains founded', 'building'],
    ['mergerBonuses', 'Dividend Hunter', 'Most merger bonus cash earned', 'coins'],
    ['sharesBought', 'Market Maker', 'Most shares purchased', 'stocks'],
  ];
  if (getHouseRules(state).placementsPerTurn > 1 || getHouseRules(state).removalsPerTurn > 0)
    categories.push(['tilesPlaced', 'City Builder', 'Most buildings placed', 'tiles']);
  for (const [field, title, detail, icon] of categories) {
    const max = Math.max(0, ...state.players.map((p) => state.metrics?.[p.id]?.[field] ?? 0));
    if (max > 0) for (const player of state.players)
      if (state.metrics?.[player.id]?.[field] === max) add(player.id, title, detail, icon);
  }
  for (const player of state.players) {
    if (awards.some((award) => award.playerId === player.id)) continue;
    const bestHolding = (state.finalSettlements ?? [])
      .map((settlement) => ({ chain: settlement.chain, shares: settlement.players.find((holder) => holder.playerId === player.id)?.shares ?? 0 }))
      .sort((a, b) => b.shares - a.shares)[0];
    const metrics = state.metrics?.[player.id];
    if (bestHolding?.shares) add(player.id, `${DEFINITIONS[bestHolding.chain].name} Backer`,
      `Held ${bestHolding.shares} ${DEFINITIONS[bestHolding.chain].name} share${bestHolding.shares === 1 ? '' : 's'} at the closing bell`, 'stocks');
    else if (metrics?.sharesBought) add(player.id, 'Active Investor',
      `Bought ${metrics.sharesBought} share${metrics.sharesBought === 1 ? '' : 's'} during the game`, 'stocks');
    else if (metrics?.tilesPlaced) add(player.id, 'Neighborhood Scout',
      `Found room for ${metrics.tilesPlaced} building${metrics.tilesPlaced === 1 ? '' : 's'} in the city`, 'tiles');
    else add(player.id, 'Steady Hand', 'Held a seat at the table until the closing bell', 'sparkles');
  }
  return awards;
}
export function encodeBoardSnapshot(state: GameState): string {
  return getMap(state.mapId).gridTiles.map((tile) => {
    const value = state.board[tile];
    return value === 'independent' ? '#' : value ? String.fromCharCode(65 + CHAIN_IDS.indexOf(value)) : '.';
  }).join('');
}
function finishGame(state: GameState, reason: string) {
  state.boardSnapshot = encodeBoardSnapshot(state);
  state.results = state.players.map((player) => ({
    playerId: player.id,
    name: player.name,
    cashBefore: player.cash,
    bonuses: 0,
    stocksValue: 0,
    total: 0,
    rank: 0,
  }));
  const activeChains = getActiveChains(state).sort(
    (a, b) => getChainSize(state, a) - getChainSize(state, b) || CHAIN_IDS.indexOf(a) - CHAIN_IDS.indexOf(b),
  );
  state.finalSettlements = activeChains.map((chain) => {
    const size = getChainSize(state, chain);
    const marketDie = getHouseRules(state).marketMode !== 'off' ? rollDie(state, 6) : undefined;
    const marketShift = marketDie ? marketShiftForDie(getHouseRules(state).marketMode, marketDie) : undefined;
    const sharePrice = getMarketPriceForSize(state, chain, size, marketShift ?? 0);
    const holdings = state.players.map((player) => player.stocks[chain]);
    const sorted = [...new Set(holdings.filter((count) => count > 0))].sort((a, b) => b - a);
    const bonuses = calculateBonuses(holdings, sharePrice, state.mode);
    return {
      chain, size, sharePrice, marketDie, marketShift,
      majorityIds: state.players.filter((_, i) => holdings[i] === sorted[0] && sorted.length > 0).map((p) => p.id),
      minorityIds: sorted.length > 1 && holdings.filter((n) => n === sorted[0]).length === 1
        ? state.players.filter((_, i) => holdings[i] === sorted[1]).map((p) => p.id) : [],
      players: state.players.map((player, index) => ({
        playerId: player.id, name: player.name, shares: holdings[index], bonus: bonuses[index],
        stockValue: holdings[index] * sharePrice,
        total: bonuses[index] + holdings[index] * sharePrice,
      })),
    };
  });
  // The 2008 scoring sequence pays every bonus first, then sells from smallest chain to largest.
  for (const settlement of state.finalSettlements) {
    const payouts = payBonuses(state, settlement.chain, settlement.size, settlement.sharePrice);
    payouts.forEach((payout, index) => {
      state.results[index].bonuses += payout;
    });
  }
  for (const settlement of state.finalSettlements) {
    const { chain, sharePrice: price } = settlement;
    state.players.forEach((player, index) => {
      const value = player.stocks[chain] * price;
      state.results[index].stocksValue += value;
      player.cash += value;
      state.bank[chain] += player.stocks[chain];
      player.stocks[chain] = 0;
    });
  }
  state.results.forEach((result, index) => {
    result.total = state.players[index].cash;
  });
  state.results.sort((a, b) => b.total - a.total);
  state.results.forEach((result) => {
    result.rank = 1 + state.results.filter((other) => other.total > result.total).length;
  });
  state.winnerIds = state.results
    .filter((result) => result.rank === 1)
    .map((result) => result.playerId);
  state.awards = makeAwards(state);
  state.phase = 'ended';
  state.endReason = reason;
  log(
    state,
    'end',
    `${reason} ${state.results
      .filter((result) => result.rank === 1)
      .map((result) => result.name)
      .join(
        ' and ',
      )} ${state.winnerIds.length > 1 ? 'share the win' : 'wins'} with ${money(state.results[0].total)}.`,
  );
}
const rollDie = (state: GameState, sides: number) => 1 + Math.floor(nextRandom(state) * sides);
export const marketShiftForDie = (mode: HouseRules['marketMode'], die: number): number =>
  mode === 'off' ? 0 : mode === 'crazy' ? [-2, -1, 0, 0, 1, 2][die - 1] : die <= 2 ? -1 : die <= 4 ? 0 : 1;
const DICE_REVEAL_GRACE_MS = 6000;
export function getInsideTiles(state: GameState, chain: ChainId): Tile[] {
  return Object.keys(state.board).filter((tile) => {
    if (state.board[tile] !== chain) return false;
    const { column, row } = tileCoordinates(tile);
    for (let rowOffset = -1; rowOffset <= 1; rowOffset++) {
      for (let columnOffset = -1; columnOffset <= 1; columnOffset++) {
        if (!rowOffset && !columnOffset) continue;
        const neighbor = `${column + columnOffset + 1}${String.fromCharCode(65 + row + rowOffset)}`;
        if (!mapHasTile(state.mapId, neighbor) || state.board[neighbor] !== chain) return false;
      }
    }
    return true;
  });
}
function settleDice(state: GameState, roundComplete: boolean, marketDue: boolean, opening = false) {
  const rules = getHouseRules(state);
  const round = Math.ceil(state.turn / state.players.length);
  let dividendDie: number | null = null;
  let stockDie: number | null = null;
  const activeHotels = getActiveChains(state);
  let selectedChain: ChainId | null = null;
  let fullClusters = 0;
  let dividendPaid = 0;
  let insideTilesReturned = 0;
  if (roundComplete && rules.dividends) {
    const hotels = getHotelChains(state);
    const clusters = [...new Set(hotels.map((chain) => DEFINITIONS[chain].tier))]
      .map((tier) => hotels.filter((chain) => DEFINITIONS[chain].tier === tier));
    fullClusters = clusters.filter((group) => group.every((chain) => getChainSize(state, chain) >= 2)).length;
    if (fullClusters) dividendDie = rollDie(state, 3);
    if (dividendDie !== null && dividendDie <= fullClusters && activeHotels.length > 0) {
      stockDie = rollDie(state, activeHotels.length);
      selectedChain = activeHotels[stockDie - 1];
      const chain = selectedChain;
      const price = getSharePrice(state, chain);
      if (!price) {
        log(state, 'dividend', `Round ${round}: dividend die ${dividendDie} succeeds; stock die ${stockDie} selects inactive ${DEFINITIONS[chain].name}. No payout.`);
      } else {
        const inside = getInsideTiles(state, chain);
        for (const shareholder of state.players) {
          const payout = Math.floor(shareholder.stocks[chain] / 3) * price;
          if (!payout) continue;
          shareholder.cash += payout;
          dividendPaid += payout;
          log(state, 'dividend', `${shareholder.name} receives ${money(payout)} from ${DEFINITIONS[chain].name} dividends.`,
            { playerId: shareholder.id, chain });
        }
        if (inside.length) {
          insideTilesReturned = inside.length;
          for (const tile of inside) {
            delete state.board[tile];
            state.bag.push(tile);
            log(state, 'remove', `${tile} returns to the draw bag after ${DEFINITIONS[chain].name}'s dividend.`, { tile, chain });
          }
          shuffle(state, state.bag);
        }
        log(state, 'dividend', `Round ${round}: dividend die ${dividendDie} succeeds; stock die ${stockDie} selects ${DEFINITIONS[chain].name}. ${money(dividendPaid)} paid${inside.length ? `; ${inside.length} inside tile${inside.length === 1 ? '' : 's'} returned to the bag` : ''}.`,
          { chain });
      }
    } else {
      log(state, 'dividend', `Round ${round}: ${fullClusters ? `dividend die ${dividendDie} misses with ${fullClusters} full cluster${fullClusters === 1 ? '' : 's'}` : 'no full hotel clusters'}. No dividend.`);
    }
  }
  let marketDie: number | null = null;
  let marketShift = state.marketShift ?? 0;
  if (marketDue && rules.marketMode !== 'off') {
    marketDie = rollDie(state, 6);
    marketShift = marketShiftForDie(rules.marketMode, marketDie);
    state.marketShift = marketShift;
    const timing = opening ? 'Before the opening turn' : rules.marketFrequency === 'turn'
      ? `Before ${state.players[(state.currentPlayer + 1) % state.players.length].name}'s turn`
      : `Round ${round}`;
    log(state, 'market', `${timing}: market die ${marketDie}. Prices are ${marketShift === 0 ? 'normal' : `${Math.abs(marketShift)} row${Math.abs(marketShift) === 1 ? '' : 's'} ${marketShift < 0 ? 'lower' : 'higher'}`}.`);
  }
  if ((roundComplete && rules.dividends) || marketDie !== null) {
    const report = {
      round, dividendDie, stockDie, chain: selectedChain, marketDie, marketShift,
      atTurn: opening ? 0 : state.turn,
      kind: opening ? 'opening' as const : roundComplete ? 'round' as const : 'turn' as const,
      fullClusters, dividendPaid, insideTilesReturned, stockDieSides: activeHotels.length,
    };
    state.lastRoundRolls = report;
    state.recentDiceRolls = [...(state.recentDiceRolls ?? []), report].slice(-state.players.length);
  }
}
function finishTurn(state: GameState) {
  if (state.endDeclared) {
    finishGame(state, 'The end of the game was declared.');
    return;
  }
  const rules = getHouseRules(state);
  const roundComplete = state.turn % state.players.length === 0;
  const completedRound = Math.ceil(state.turn / state.players.length);
  const marketDue = rules.marketMode !== 'off' && (rules.marketFrequency === 'turn' ||
    (roundComplete && (rules.marketFrequency === 'round' ||
      rules.marketFrequency === 'two-rounds' && completedRound % 2 === 0 ||
      rules.marketFrequency === 'three-rounds' && completedRound % 3 === 0)));
  if (roundComplete || marketDue) settleDice(state, roundComplete, marketDue);
  // A digital deadlock safeguard: if no remaining or held tile can ever be played, settle the table.
  const anyoneCanPlay = state.players.some((player) => getLegalTiles(state, player.id).length > 0);
  const drawableCanPlay = state.bag.some((tile) => analyzeTile(state, tile).legal);
  const removalCanRestore = !anyoneCanPlay && !drawableCanPlay && getHouseRules(state).removalsPerTurn > 0 && Object.keys(state.board).some((tile) => {
    if (!canRemoveTile({ ...state, turn: state.turn + 1 }, tile)) return false;
    const board = { ...state.board };
    delete board[tile];
    const afterRemoval = { ...state, board };
    return analyzeTile(afterRemoval, tile).legal ||
      state.players.some((player) => player.hand.some((held) => analyzeTile(afterRemoval, held).legal)) ||
      state.bag.some((held) => analyzeTile(afterRemoval, held).legal);
  });
  // The printed FAQ allows a fully blocked rack to be exchanged, including temporarily blocked tiles.
  if (!anyoneCanPlay && !drawableCanPlay && !removalCanRestore) {
    finishGame(state, 'No playable building tiles remain.');
    return;
  }
  state.currentPlayer = (state.currentPlayer + 1) % state.players.length;
  state.turn += 1;
  state.phase = 'place';
  state.tilePlacedThisTurn = false;
  state.placementsThisTurn = 0;
  state.removalsThisTurn = 0;
  const seconds = getHouseRules(state).turnTimerSeconds;
  const diceJustRolled = state.lastRoundRolls?.atTurn === state.turn - 1;
  state.turnDeadlineAt = seconds ? Date.now() + seconds * 1000 + (diceJustRolled ? DICE_REVEAL_GRACE_MS : 0) : null;
  state.foundingTiles = [];
  log(state, 'turn', `${state.players[state.currentPlayer].name}'s turn.`, {
    playerId: state.players[state.currentPlayer].id,
  });
}
function drawAndFinish(state: GameState) {
  const player = state.players[state.currentPlayer];
  // Refill the rack after a multi-placement turn, without drawing extra tiles for a pass.
  while (player.hand.length < 6 && state.bag.length) player.hand.push(state.bag.pop()!);
  finishTurn(state);
}
function afterPlacement(state: GameState) {
  const limit = getHouseRules(state).placementsPerTurn;
  state.phase = (state.placementsThisTurn ?? 0) < limit && state.players[state.currentPlayer].hand.length ? 'place' : 'buy';
}
function finishMerger(state: GameState) {
  const merger = state.merger!;
  const connection = independentConnection(state, merger.tile);
  for (const tile of connection.tiles) state.board[tile] = merger.survivor!;
  log(
    state,
    'merger',
    `${DEFINITIONS[merger.survivor!].name} now spans ${getChainSize(state, merger.survivor!)} buildings.`,
    { chain: merger.survivor! },
  );
  state.merger = null;
  afterPlacement(state);
}
function nextAcquisition(state: GameState) {
  const merger = state.merger!;
  merger.acquired = null;
  if (!merger.remaining.length) {
    finishMerger(state);
    return;
  }
  const largest = Math.max(...merger.remaining.map((chain) => merger.sizes[chain]!));
  merger.orderOptions = merger.remaining.filter((chain) => merger.sizes[chain] === largest);
  if (merger.orderOptions.length > 1) state.phase = 'merger-order';
  else beginAcquisition(state, merger.orderOptions[0]);
}
function beginAcquisition(state: GameState, chain: ChainId) {
  const merger = state.merger!;
  merger.acquired = chain;
  merger.remaining = merger.remaining.filter((item) => item !== chain);
  merger.orderOptions = [];
  merger.sharePrice = getMarketPriceForSize(state, chain, merger.sizes[chain]!);
  const holdings = state.players.map((player) => player.stocks[chain]);
  const levels = [...new Set(holdings.filter((count) => count > 0))].sort((a, b) => b - a);
  const bonuses = calculateBonuses(holdings, merger.sharePrice, state.mode);
  log(
    state,
    'merger',
    `${DEFINITIONS[merger.survivor!].name} acquires ${DEFINITIONS[chain].name} (${merger.sizes[chain]} buildings). Its shares settle at ${money(merger.sharePrice)}.`,
    { chain, payout: {
      chain, survivor: merger.survivor!, size: merger.sizes[chain]!, sharePrice: merger.sharePrice,
      majorityIds: state.players.filter((_, i) => levels.length > 0 && holdings[i] === levels[0]).map((p) => p.id),
      minorityIds: levels.length > 1 && holdings.filter((count) => count === levels[0]).length === 1
        ? state.players.filter((_, i) => holdings[i] === levels[1]).map((p) => p.id) : [],
      players: state.players.map((player, i) => ({ playerId: player.id, shares: holdings[i], bonus: bonuses[i] })),
    } },
  );
  payBonuses(state, chain, merger.sizes[chain]!);
  for (const tile of Object.keys(state.board))
    if (state.board[tile] === chain) state.board[tile] = merger.survivor!;
  merger.shareholders = Array.from(
    { length: state.players.length },
    (_, i) => (state.currentPlayer + i) % state.players.length,
  ).filter((index) => state.players[index].stocks[chain] > 0);
  merger.shareholderCursor = 0;
  if (merger.shareholders.length) state.phase = 'merger-shares';
  else nextAcquisition(state);
}
function chooseSurvivor(state: GameState, chain: ChainId) {
  const merger = state.merger!;
  merger.survivor = chain;
  merger.remaining = merger.chains.filter((item) => item !== chain);
  nextAcquisition(state);
}
export function applyAction(previous: GameState, action: GameAction): GameState {
  assert(
    previous.version === 2 && previous.ruleset === '2008',
    'This save uses a different edition. Start a new 2008 game.',
  );
  assert(previous.phase !== 'ended', 'This game has finished. Start a new table to play again.');
  assert(
    action && typeof action === 'object' && typeof action.type === 'string',
    'Choose a valid game action.',
  );
  const state = structuredClone(previous);
  const player = state.players[state.currentPlayer];
  switch (action.type) {
    case 'place': {
      assert(
        state.phase === 'place',
        'Finish the current decision before placing another building.',
      );
      assert((state.placementsThisTurn ?? 0) < getHouseRules(state).placementsPerTurn,
        'You have already placed the maximum number of tiles this turn.');
      assert(player.hand.includes(action.tile), 'That tile is not in your rack.');
      const analysis = analyzeTile(state, action.tile);
      assert(analysis.legal, analysis.reason ?? 'That tile cannot be played.');
      player.hand.splice(player.hand.indexOf(action.tile), 1);
      state.board[action.tile] = 'independent';
      state.lastPlacedTile = action.tile;
      state.tilePlacedThisTurn = true;
      state.placementsThisTurn = (state.placementsThisTurn ?? 0) + 1;
      metric(state, player.id).tilesPlaced++;
      log(state, 'tile', `${player.name} places ${action.tile}.`, {
        playerId: player.id,
        tile: action.tile,
      });
      if (analysis.kind === 'independent') afterPlacement(state);
      else if (analysis.kind === 'found') {
        state.foundingTiles = analysis.connectedTiles;
        state.phase = 'found';
      } else if (analysis.kind === 'grow') {
        for (const tile of analysis.connectedTiles) state.board[tile] = analysis.chains[0];
        log(
          state,
          'tile',
          `${DEFINITIONS[analysis.chains[0]].name} grows to ${getChainSize(state, analysis.chains[0])} buildings.`,
          { chain: analysis.chains[0] },
        );
        afterPlacement(state);
      } else {
        metric(state, player.id).mergesCaused++;
        const sizes = Object.fromEntries(
          analysis.chains.map((chain) => [chain, getChainSize(state, chain)]),
        ) as Partial<Stocks>;
        const largest = Math.max(...Object.values(sizes));
        const survivorOptions = analysis.chains.filter((chain) => sizes[chain] === largest);
        state.merger = {
          tile: action.tile,
          chains: analysis.chains,
          sizes,
          survivor: null,
          survivorOptions,
          remaining: [],
          orderOptions: [],
          acquired: null,
          sharePrice: 0,
          shareholders: [],
          shareholderCursor: 0,
        };
        if (survivorOptions.length > 1) state.phase = 'merger-survivor';
        else chooseSurvivor(state, survivorOptions[0]);
      }
      break;
    }
    case 'finish-placing':
      assert(state.phase === 'place' && (state.placementsThisTurn ?? 0) > 0,
        'Place at least one tile before finishing placement.');
      state.phase = 'buy';
      break;
    case 'remove':
      assert(state.phase === 'place', 'Remove a building during your placement step.');
      assert((state.removalsThisTurn ?? 0) < getHouseRules(state).removalsPerTurn, 'You have used this turn’s removals.');
      assert(canRemoveTile(state, action.tile), 'Choose a tile that leaves every hotel chain intact.');
      delete state.board[action.tile];
      state.bag.push(action.tile);
      shuffle(state, state.bag);
      state.removalsThisTurn = (state.removalsThisTurn ?? 0) + 1;
      if (state.lastPlacedTile === action.tile) state.lastPlacedTile = null;
      log(state, 'remove', `${player.name} removes ${action.tile}; it returns to the draw bag.`, { playerId: player.id, tile: action.tile });
      break;
    case 'replace-dead-tiles': {
      assert(state.phase === 'place', 'Replace permanently blocked tiles during placement.');
      const revealed = player.hand.filter((tile) => analyzeTile(state, tile).permanent);
      assert(revealed.length > 0, 'Your rack has no permanently unplayable tiles.');
      player.hand = player.hand.filter((tile) => !revealed.includes(tile));
      state.discarded.push(...revealed);
      const before = player.hand.length;
      while (player.hand.length < 6 && state.bag.length) player.hand.push(state.bag.pop()!);
      log(
        state,
        'discard',
        `${player.name} reveals and sets aside permanently unplayable ${revealed.join(', ')}, then draws ${player.hand.length - before} replacement tile${player.hand.length - before === 1 ? '' : 's'}. Their turn continues.`,
        { playerId: player.id },
      );
      break;
    }
    case 'exchange-hand': {
      assert(state.phase === 'place' && (state.placementsThisTurn ?? 0) === 0 && (state.removalsThisTurn ?? 0) === 0,
        'Exchange an unplayable rack at the beginning of your turn.');
      assert(getLegalTiles(state).length === 0,
        'Your rack has a playable tile and cannot be exchanged.');
      assert(state.bag.length > 0, 'The tile bag is empty. No replacement tiles remain.');
      const revealed = [...player.hand];
      state.discarded.push(...revealed);
      player.hand = [];
      while (player.hand.length < 6 && state.bag.length) player.hand.push(state.bag.pop()!);
      log(state, 'discard',
        `${player.name} reveals and sets aside the entire ${revealed.length}-tile rack (${revealed.join(', ')}), then draws ${player.hand.length} replacement tile${player.hand.length === 1 ? '' : 's'}. Their turn continues.`,
        { playerId: player.id });
      break;
    }
    case 'pass':
      assert(state.phase === 'place', 'You may skip placement only at the start of your turn.');
      assert(getLegalTiles(state).length === 0, 'You have a playable tile and must place one.');
      assert(state.bag.length === 0 || (state.removalsThisTurn ?? 0) > 0,
        'Exchange your unplayable rack before continuing this turn.');
      log(state, 'tile', `${player.name} has no playable tile and skips placement.`, {
        playerId: player.id,
      });
      state.phase = 'buy';
      break;
    case 'found': {
      assert(state.phase === 'found', 'No new chain is waiting to be founded.');
      assert(
        validChain(action.chain) && getAvailableChains(state).includes(action.chain),
        'Choose a chain that is not already on the board.',
      );
      for (const tile of state.foundingTiles) state.board[tile] = action.chain;
      const founderShareAvailable = state.bank[action.chain] > 0;
      if (founderShareAvailable) {
        player.stocks[action.chain] += 1;
        state.bank[action.chain] -= 1;
      }
      metric(state, player.id).chainsFounded++;
      log(
        state,
        'found',
        `${player.name} founds ${DEFINITIONS[action.chain].name}${founderShareAvailable ? ' and receives one free founder share' : '. No founder share remains, so no bonus is awarded'}.`,
        { playerId: player.id, chain: action.chain, tile: state.lastPlacedTile ?? undefined },
      );
      state.foundingTiles = [];
      afterPlacement(state);
      break;
    }
    case 'choose-survivor':
      assert(state.phase === 'merger-survivor' && state.merger, 'No survivor decision is pending.');
      assert(
        state.merger.survivorOptions.includes(action.chain),
        'Only a largest chain may survive this merger.',
      );
      chooseSurvivor(state, action.chain);
      break;
    case 'choose-acquired':
      assert(
        state.phase === 'merger-order' && state.merger,
        'No acquisition order decision is pending.',
      );
      assert(
        state.merger.orderOptions.includes(action.chain),
        'Resolve the largest remaining acquired chain first.',
      );
      beginAcquisition(state, action.chain);
      break;
    case 'resolve-shares': {
      assert(
        state.phase === 'merger-shares' && state.merger?.acquired && state.merger.survivor,
        'No merger shares need resolving.',
      );
      const merger = state.merger;
      const acquired = merger.acquired!;
      const survivor = merger.survivor!;
      const actor = getCurrentActor(state);
      assert(
        Number.isInteger(action.sell) &&
          action.sell >= 0 &&
          Number.isInteger(action.trade) &&
          action.trade >= 0 &&
          action.trade % 2 === 0,
        'Sell a whole number of shares and trade in pairs of two.',
      );
      assert(
        action.sell + action.trade <= actor.stocks[acquired],
        'You cannot sell or trade more shares than you own.',
      );
      assert(
        action.trade / 2 <= state.bank[survivor],
        'The bank does not have enough surviving-chain shares for that trade.',
      );
      actor.stocks[acquired] -= action.sell + action.trade;
      state.bank[acquired] += action.sell + action.trade;
      actor.cash += action.sell * merger.sharePrice;
      metric(state, actor.id).sharesSold += action.sell;
      actor.stocks[survivor] += action.trade / 2;
      state.bank[survivor] -= action.trade / 2;
      log(
        state,
        'shares',
        `${actor.name}: sells ${action.sell}, trades ${action.trade} for ${action.trade / 2} ${DEFINITIONS[survivor].name}, and keeps ${actor.stocks[acquired]} ${DEFINITIONS[acquired].name} shares.`,
        { playerId: actor.id, chain: acquired },
      );
      merger.shareholderCursor += 1;
      if (merger.shareholderCursor >= merger.shareholders.length) nextAcquisition(state);
      break;
    }
    case 'buy': {
      assert(
        state.phase === 'buy',
        'Place a building and finish its decisions before buying shares.',
      );
      assert(
        action.stocks && typeof action.stocks === 'object' && !Array.isArray(action.stocks),
        'Choose the shares to buy.',
      );
      assert(!action.sellStocks || (typeof action.sellStocks === 'object' && !Array.isArray(action.sellStocks)),
        'Choose valid shares to sell.');
      const rules = getHouseRules(state);
      let sold = 0;
      let proceeds = 0;
      for (const [chain, quantity] of Object.entries(action.sellStocks ?? {})) {
        assert(validChain(chain), 'That hotel chain does not exist.');
        assert(Number.isInteger(quantity) && quantity >= 0, 'Share quantities must be nonnegative whole numbers.');
        if (!quantity) continue;
        assert(rules.hotelChains.includes(chain), 'That hotel chain is not available in this game.');
        assert(quantity <= player.stocks[chain], 'You cannot sell more shares than you own.');
        sold += quantity;
        proceeds += getSharePrice(state, chain) * quantity;
      }
      assert(sold === 0 || rules.trading, 'Turn trading is not enabled for this table.');
      assert(sold <= 3, 'You may sell at most three shares on your turn.');
      let count = 0;
      let cost = 0;
      for (const [chain, quantity] of Object.entries(action.stocks)) {
        assert(validChain(chain), 'That hotel chain does not exist.');
        assert(
          Number.isInteger(quantity) && quantity >= 0,
          'Share quantities must be nonnegative whole numbers.',
        );
        if (!quantity) continue;
        assert(rules.hotelChains.includes(chain), 'That hotel chain is not available in this game.');
        assert(getChainSize(state, chain) >= 2, 'You can only buy shares in active chains.');
        assert(
          quantity <= state.bank[chain] + (action.sellStocks?.[chain] ?? 0),
          `There are not enough ${DEFINITIONS[chain].name} shares in the bank.`,
        );
        count += quantity;
        cost += getSharePrice(state, chain) * quantity;
      }
      assert(count <= rules.buyLimit + sold, `You may buy at most ${rules.buyLimit + sold} shares this turn.`);
      assert(cost <= player.cash + proceeds, 'You do not have enough cash for that purchase.');
      if (sold) {
        for (const [chain, quantity] of Object.entries(action.sellStocks!) as [ChainId, number][]) {
          if (!quantity) continue;
          player.stocks[chain] -= quantity;
          state.bank[chain] += quantity;
        }
        player.cash += proceeds;
        metric(state, player.id).sharesSold += sold;
        const descriptions = Object.entries(action.sellStocks!)
          .filter(([, quantity]) => quantity > 0)
          .map(([chain, quantity]) => `${quantity} ${DEFINITIONS[chain as ChainId].name}`);
        log(state, 'sell', `${player.name} sells ${descriptions.join(', ')} for ${money(proceeds)}.`, { playerId: player.id });
      }
      for (const [chain, quantity] of Object.entries(action.stocks) as [ChainId, number][]) {
        if (!quantity) continue;
        player.stocks[chain] += quantity;
        state.bank[chain] -= quantity;
      }
      player.cash -= cost;
      metric(state, player.id).sharesBought += count;
      metric(state, player.id).cashSpent += cost;
      const descriptions = Object.entries(action.stocks)
        .filter(([, n]) => n! > 0)
        .map(([chain, n]) => `${n} ${DEFINITIONS[chain as ChainId].name}`);
      log(
        state,
        'buy',
        count
          ? `${player.name} buys ${descriptions.join(', ')} for ${money(cost)}.`
          : `${player.name} keeps their cash and passes on shares.`,
        { playerId: player.id },
      );
      drawAndFinish(state);
      break;
    }
    case 'declare-end':
      assert(
        canEndGame(state),
        `After playing a tile, you may declare the game over if a chain reaches ${getMap(state.mapId).endSize} buildings or the map’s all-safe condition is met.`,
      );
      assert(!state.endDeclared, 'The game will already end after this turn.');
      state.endDeclared = true;
      log(
        state,
        'end',
        `${player.name} declares the game over. This turn will finish before final payouts.`,
        { playerId: player.id },
      );
      break;
    default:
      throw new Error('Unknown game action.');
  }
  state.revision += 1;
  return state;
}

/** Evaluate every acquired chain, including a tied largest chain. Cash arriving
 * now is more useful to a cash-starved player than the same eventual payout.
 * Include survivor growth and the finite supply of two-for-one exchanges. */
function strategistMergerValue(state: GameState, chains: ChainId[], survivor: ChainId, addedTiles: number): number {
  const actor = getCurrentActor(state);
  const actorIndex = state.players.findIndex((player) => player.id === actor.id);
  const finalSize = chains.reduce((sum, chain) => sum + getChainSize(state, chain), addedTiles);
  const priceBefore = getSharePrice(state, survivor);
  const priceAfter = getMarketPriceForSize(state, survivor, finalSize);
  const survivorHoldings = state.players.map((player) => player.stocks[survivor]);
  const bonusesBefore = calculateBonuses(survivorHoldings, priceBefore);
  const liquidity = state.players.map((player) => Math.max(0, 1 - player.cash / 2400));
  const gains = state.players.map((player) => player.stocks[survivor] * (priceAfter - priceBefore));
  let certificates = state.bank[survivor];
  const acquired = chains.filter((chain) => chain !== survivor)
    .sort((a, b) => getChainSize(state, b) - getChainSize(state, a));
  for (const chain of acquired) {
    const price = getSharePrice(state, chain);
    const payouts = calculateBonuses(state.players.map((player) => player.stocks[chain]), price);
    // Exchanges resolve in turn order; rivals do not all have access to the same stock.
    for (let offset = 0; offset < state.players.length; offset++) {
      const index = (state.currentPlayer + offset) % state.players.length;
      const player = state.players[index];
      const held = player.stocks[chain];
      const reserve = Math.min(held, Math.ceil(Math.max(0, 1800 - player.cash - payouts[index]) / price));
      const trade = Math.min(certificates, Math.floor((held - reserve) / 2));
      certificates -= trade;
      survivorHoldings[index] += trade;
      gains[index] += payouts[index] * (1 + liquidity[index] * 0.75)
        + held * price * liquidity[index] * 0.25
        + trade * Math.max(0, priceAfter - 2 * price);
    }
  }
  const bonusesAfter = calculateBonuses(survivorHoldings, priceAfter);
  gains.forEach((_, index) => { gains[index] += (bonusesAfter[index] - bonusesBefore[index]) * 0.5; });
  const ownWealth = getNetWorth(state, actor);
  const rivalGains = gains.filter((_, index) => index !== actorIndex);
  const strongestRivalGain = Math.max(0, ...gains.map((gain, index) => index === actorIndex ? 0
    : gain * (getNetWorth(state, state.players[index]) >= ownWealth ? 1.15 : 0.95)));
  return (gains[actorIndex] - strongestRivalGain - rivalGains.reduce((sum, value) => sum + value, 0) / rivalGains.length * 0.15) / 180;
}

/** Estimate contested bonus positions instead of treating today's single-share
 * majority as guaranteed. A depleted bank makes present rankings more certain. */
function contestedBonuses(state: GameState, chain: ChainId, holdings: number[], buyer: number, remaining: number): number[] {
  const price = getSharePrice(state, chain);
  if (!remaining || state.endDeclared) return calculateBonuses(holdings, price);
  const largest = Math.max(...holdings);
  const uncertainty = remaining > 8 ? 1.5 : 0.8;
  const weights = holdings.map((held, i) => held > 0 ? Math.exp((held - largest) / uncertainty)
    : i !== buyer && state.players[i].cash >= price ? 0.35 * Math.exp((1 - largest) / uncertainty) : 0);
  const total = weights.reduce((sum, weight) => sum + weight, 0);
  if (!total) return holdings.map(() => 0);
  return weights.map((weight, i) => {
    if (!weight) return 0;
    const first = weight / total;
    const second = total === weight ? 1 : weights.reduce((chance, rival, j) =>
      i === j || !rival ? chance : chance + rival / total * weight / (total - rival), 0);
    return price * (10 * first + 5 * second);
  });
}

/** Bots use only the public table and their own rack; no future draw or opponent-hand access. */
export function chooseBotAction(state: GameState): GameAction {
  assert(state.phase !== 'ended', 'This game is finished.');
  const actor = getCurrentActor(state);
  const difficulty = state.botDifficulty ?? 'standard';
  if (canEndGame(state) && !state.endDeclared) {
    const marketMode = getHouseRules(state).marketMode;
    const closingValues = getActiveChains(state).map((chain) => {
      const prices = marketMode === 'off' ? [getSharePrice(state, chain)]
        : [1, 2, 3, 4, 5, 6].map((die) => getMarketPriceForSize(state, chain, getChainSize(state, chain), marketShiftForDie(marketMode, die)));
      const holdings = state.players.map((player) => player.stocks[chain]);
      return prices.map((price) => calculateBonuses(holdings, price).map((bonus, i) => bonus + holdings[i] * price));
    });
    const projected = state.players.map((player, index) => ({
      id: player.id,
      // Closing markets are uncertain. Average the public die outcomes; never inspect RNG.
      total: player.cash + closingValues.reduce((sum, outcomes) => sum
        + outcomes.reduce((total, outcome) => total + outcome[index], 0) / outcomes.length, 0),
    }));
    const own = projected.find((p) => p.id === actor.id)!.total;
    const lead = Math.max(...projected.filter((p) => p.id !== actor.id).map((p) => p.total));
    if (difficulty === 'casual' || own >= lead) return { type: 'declare-end' };
  }
  const ownShares = (chain: ChainId) => actor.stocks[chain];
  const rivalMaximum = (chain: ChainId) =>
    Math.max(0, ...state.players.filter((p) => p.id !== actor.id).map((p) => p.stocks[chain]));
  switch (state.phase) {
    case 'place': {
      const tiles = getLegalTiles(state);
      if (!tiles.length) return (state.placementsThisTurn ?? 0) > 0
        ? { type: 'finish-placing' }
        : state.bag.length && (state.removalsThisTurn ?? 0) === 0
          ? { type: 'exchange-hand' } : { type: 'pass' };
      if (actor.hand.some((tile) => analyzeTile(state, tile).permanent))
        return { type: 'replace-dead-tiles' };
      const score = (tile: Tile) => {
        const analysis = analyzeTile(state, tile);
        const coords = tileCoordinates(tile);
        const map = getMap(state.mapId);
        let value = 4 - (Math.abs(coords.column - (map.columns - 1) / 2) + Math.abs(coords.row - (map.rows - 1) / 2)) * 0.13;
        if (analysis.kind === 'found') value += 14 + (actor.cash > 600 ? 5 : 0);
        if (analysis.kind === 'grow')
          value += 5 + ownShares(analysis.chains[0]) * 1.3 - rivalMaximum(analysis.chains[0]) * 0.5;
        if (analysis.kind === 'merge') {
          value += 8;
          const largest = Math.max(...analysis.chains.map((chain) => getChainSize(state, chain)));
          if (difficulty === 'strategist') {
            const survivors = analysis.chains.filter((chain) => getChainSize(state, chain) === largest);
            value += Math.max(...survivors.map((survivor) => strategistMergerValue(state, analysis.chains, survivor, analysis.connectedTiles.length)));
          } else {
            for (const chain of analysis.chains) {
              const size = getChainSize(state, chain);
              if (size < largest) {
                const payouts = calculateBonuses(
                  state.players.map((p) => p.stocks[chain]),
                  getSharePrice(state, chain),
                  state.mode,
                );
                const index = state.players.findIndex((p) => p.id === actor.id);
                value += payouts[index] / (difficulty === 'casual' ? 300 : 250) + ownShares(chain) * (actor.cash < 1000 ? 1.7 : 0.5);
                const worstRival = Math.max(...payouts.map((payout, i) => {
                  if (i === index) return 0;
                  const rival = state.players[i];
                  const saleCash = rival.stocks[chain] * getSharePrice(state, chain);
                  return payout + saleCash * (rival.cash < 1500 ? 0.6 : 0.15);
                }));
                value -= worstRival / (difficulty === 'casual' ? 900 : 420);
              }
            }
          }
        }
        const handNeighbors = getNeighbors(tile, state.mapId).filter((t) => actor.hand.includes(t)).length;
        return value + handNeighbors * 2;
      };
      tiles.sort((a, b) => score(b) - score(a));
      return { type: 'place', tile: tiles[0] };
    }
    case 'found': {
      const options = getAvailableChains(state);
      options.sort(
        (a, b) =>
          (ownShares(b) - rivalMaximum(b)) * 10 +
          DEFINITIONS[b].tier -
          ((ownShares(a) - rivalMaximum(a)) * 10 + DEFINITIONS[a].tier),
      );
      return { type: 'found', chain: options[0] };
    }
    case 'merger-survivor': {
      const options = [...state.merger!.survivorOptions];
      if (difficulty === 'strategist') {
        const added = independentConnection(state, state.merger!.tile).tiles.length;
        options.sort((a, b) => strategistMergerValue(state, state.merger!.chains, b, added)
          - strategistMergerValue(state, state.merger!.chains, a, added));
        return { type: 'choose-survivor', chain: options[0] };
      }
      options.sort(
        (a, b) => ownShares(b) - rivalMaximum(b) * 0.5 - (ownShares(a) - rivalMaximum(a) * 0.5),
      );
      return { type: 'choose-survivor', chain: options[0] };
    }
    case 'merger-order': {
      const options = [...state.merger!.orderOptions];
      options.sort((a, b) => ownShares(b) - ownShares(a));
      return { type: 'choose-acquired', chain: options[0] };
    }
    case 'merger-shares': {
      const merger = state.merger!;
      const held = actor.stocks[merger.acquired!];
      if (difficulty === 'strategist') {
        const survivor = merger.survivor!;
        const finalSize = merger.chains.reduce((sum, chain) => sum + merger.sizes[chain]!, 0)
          + independentConnection(state, merger.tile).tiles.length;
        const finalPrice = getMarketPriceForSize(state, survivor, finalSize);
        const index = state.players.findIndex((player) => player.id === actor.id);
        let bestTrade = 0, bestValue = -Infinity;
        for (let certificates = 0; certificates <= Math.min(Math.floor(held / 2), state.bank[survivor]); certificates++) {
          const cash = actor.cash + (held - certificates * 2) * merger.sharePrice;
          const holdings = state.players.map((player, i) => player.stocks[survivor] + (i === index ? certificates : 0));
          const bonuses = calculateBonuses(holdings, finalPrice);
          const rivalBonus = Math.max(...bonuses.filter((_, i) => i !== index));
          const value = cash + certificates * finalPrice + (bonuses[index] - rivalBonus) * 0.5
            - Math.max(0, 1800 - cash) * 0.75;
          if (value > bestValue) { bestValue = value; bestTrade = certificates * 2; }
        }
        return { type: 'resolve-shares', sell: held - bestTrade, trade: bestTrade };
      }
      const reserveNeeded = Math.max(0, 1800 - actor.cash);
      const reserveShares = Math.min(held, Math.ceil(reserveNeeded / merger.sharePrice));
      const trade =
        Math.min(Math.floor((held - reserveShares) / 2), state.bank[merger.survivor!]) * 2;
      return { type: 'resolve-shares', sell: held - trade, trade };
    }
    case 'buy': {
      const stocks: Partial<Stocks> = {};
      const sellStocks: Partial<Stocks> = {};
      if (getHouseRules(state).trading) {
        for (const chain of getHotelChains(state)) {
          if (getChainSize(state, chain) > 0) continue;
          const quantity = Math.min(3 - Object.values(sellStocks).reduce((sum, n) => sum + (n ?? 0), 0), actor.stocks[chain]);
          if (quantity > 0) sellStocks[chain] = quantity;
        }
      }
      const sold = Object.values(sellStocks).reduce((sum, n) => sum + (n ?? 0), 0);
      let cash = actor.cash;
      if (difficulty === 'strategist') {
        const index = state.players.findIndex((player) => player.id === actor.id);
        let left = getHouseRules(state).buyLimit + sold;
        while (left > 0) {
          let best: { chain: ChainId; quantity: number; score: number } | undefined;
          for (const chain of getActiveChains(state)) {
            const price = getSharePrice(state, chain);
            const remaining = state.bank[chain] - (stocks[chain] ?? 0);
            const holdings = state.players.map((player, i) => player.stocks[chain] + (i === index ? stocks[chain] ?? 0 : 0));
            const before = contestedBonuses(state, chain, holdings, index, remaining);
            // Consider whole purchases so a two/three-share bid can overtake a
            // rival even when its first certificate alone changes no bonus.
            for (let count = 1; count <= Math.min(left, remaining, Math.floor(cash / price)); count++) {
              const after = contestedBonuses(state, chain, holdings.map((held, i) => held + (i === index ? count : 0)), index, remaining - count);
              const denial = Math.max(...before.filter((_, i) => i !== index)) - Math.max(...after.filter((_, i) => i !== index));
              const reserveCost = state.endDeclared || state.bag.length < 15 ? 0
                : Math.max(0, 600 - (cash - count * price)) * 0.5;
              const score = (after[index] - before[index] + denial * 0.25 - reserveCost) / (count * price);
              if (score > 0.2 && (!best || score > best.score)) best = { chain, quantity: count, score };
            }
          }
          if (!best) break;
          stocks[best.chain] = (stocks[best.chain] ?? 0) + best.quantity;
          cash -= getSharePrice(state, best.chain) * best.quantity;
          left -= best.quantity;
        }
        return { type: 'buy', stocks, sellStocks };
      }
      for (let count = 0; count < getHouseRules(state).buyLimit + sold; count++) {
        const choices = getActiveChains(state).filter(
          (chain) =>
            state.bank[chain] > (stocks[chain] ?? 0) && getSharePrice(state, chain) <= cash,
        );
        if (!choices.length) break;
        const score = (chain: ChainId) => {
          const held = ownShares(chain) + (stocks[chain] ?? 0);
          const rival = rivalMaximum(chain);
          const price = getSharePrice(state, chain);
          const size = getChainSize(state, chain);
          const base = (
            10 +
            (held === 0 ? 9 : 0) +
            (held <= rival ? 12 / (rival - held + 1) : 4 / (held - rival)) +
            (size >= 11 ? 3 : 5) -
            price / 250 -
            held * 0.4
          );
          if (difficulty === 'casual') return base + DEFINITIONS[chain].tier * 2;
          return base;
        };
        choices.sort((a, b) => score(b) - score(a));
        const chain = choices[0];
        // Preserve a small founding reserve unless settlement is imminent.
        if (cash - getSharePrice(state, chain) < 300 && state.bag.length > 20 && !state.endDeclared)
          break;
        stocks[chain] = (stocks[chain] ?? 0) + 1;
        cash -= getSharePrice(state, chain);
      }
      return { type: 'buy', stocks, sellStocks };
    }
  }
}

/** Complete an expired turn with safe automatic decisions. The server checks this before actions. */
export function expireTurn(previous: GameState, now = Date.now()): GameState {
  if (previous.phase === 'ended' || !previous.turnDeadlineAt || now < previous.turnDeadlineAt) return previous;
  let state = structuredClone(previous);
  const expiredTurn = state.turn;
  state.turnDeadlineAt = null;
  log(state, 'timeout', `${state.players[state.currentPlayer].name}'s turn timer expired; remaining decisions were completed automatically.`,
    { playerId: state.players[state.currentPlayer].id });
  for (let i = 0; i < 256 && state.phase !== 'ended' && state.turn === expiredTurn; i++) {
    const action: GameAction = state.phase === 'buy'
      ? { type: 'buy', stocks: {} }
      : state.phase === 'place' && (state.placementsThisTurn ?? 0) > 0
        ? { type: 'finish-placing' }
        : chooseBotAction(state);
    state = applyAction(state, action.type === 'declare-end' ? { type: 'buy', stocks: {} } : action);
  }
  assert(state.phase === 'ended' || state.turn !== expiredTurn, 'Timed turn could not be completed.');
  return state;
}
