// Generated by supabase/sync-engine.mjs. Edit src/game/maps.ts.
import type { MapId, Tile } from './types.ts';

export interface MapPalette {
  name: string;
  canvas: string;
  frame: string;
  tile: string;
  accent: string;
  ink: string;
  void: string;
}
export interface MapDefinition {
  id: MapId;
  name: string;
  description: string;
  tiles: Tile[];
  gridTiles: Tile[];
  columns: number;
  rows: number;
  maxPlayers: number;
  endSize: number;
  feature: string;
  palette: MapPalette;
}

const tile = (column: number, row: number) => `${column + 1}${String.fromCharCode(65 + row)}`;
const makeSizedMap = (
  id: MapId, name: string, description: string, feature: string, palette: MapPalette,
  columns: number, rows: number, maxPlayers: number, endSize: number,
  include: (c: number, r: number) => boolean,
): MapDefinition => {
  if (columns < 1 || columns > 99 || rows < 1 || rows > 26)
    throw new Error(`Invalid dimensions for ${id}`);
  const gridTiles = Array.from({ length: columns * rows }, (_, i) => tile(i % columns, Math.floor(i / columns)));
  return {
    id, name, description, feature, palette, columns, rows, maxPlayers, endSize, gridTiles,
    tiles: gridTiles.filter((coordinate) => {
      const column = Number(coordinate.slice(0, -1)) - 1;
      const row = coordinate.charCodeAt(coordinate.length - 1) - 65;
      return include(column, row);
    }),
  };
};
const makeMap = (
  id: MapId, name: string, description: string, feature: string, palette: MapPalette,
  include: (c: number, r: number) => boolean,
): MapDefinition => makeSizedMap(id, name, description, feature, palette, 12, 9, 6, 41, include);
/** Each # is one physical tile. Dots are absent from both the bag and the board. */
const shaped = (
  id: MapId, name: string, description: string, feature: string, palette: MapPalette,
  rows: readonly string[],
) => {
  if (rows.length !== 9 || rows.some((row) => row.length !== 12 || /[^#.]/.test(row)))
    throw new Error(`Invalid footprint for ${id}`);
  return makeMap(id, name, description, feature, palette, (c, r) => rows[r][c] === '#');
};

/** Printed rules remain the default; larger custom tables extend the tile grid and seat limit. */
export const MAPS: MapDefinition[] = [
  makeMap('classic', 'The Classic', 'The complete 2008 board.', 'The original city',
    { name: 'Sage & stone', canvas: '#f1f4e9', frame: '#e0e6d6', tile: '#f8f9f0', accent: '#69934b', ink: '#456144', void: '#edf1e6' }, () => true),
  makeMap('corner-plazas', 'Corner Plazas', 'Four open plazas push growth toward the center.', 'Open corners',
    { name: 'Rose garden', canvas: '#fff0ed', frame: '#efdad8', tile: '#fff9f6', accent: '#a95b72', ink: '#633e50', void: '#f5d7d6' },
    (c, r) => !((c < 2 || c > 9) && (r < 2 || r > 6))),
  makeMap('riverwalk', 'Riverwalk', 'Two waterfront promenades narrow the middle.', 'Side channels',
    { name: 'Blue harbor', canvas: '#e8f5f6', frame: '#cde4e9', tile: '#f5fcfb', accent: '#397f9a', ink: '#31546a', void: '#b2d7e4' },
    (c, r) => !((c < 2 || c > 9) && r >= 3 && r <= 5)),
  makeMap('grand-avenue', 'Grand Avenue', 'A broad north–south corridor opens the edges.', 'Open gateways',
    { name: 'Slate boulevard', canvas: '#e8edf2', frame: '#cdd9e3', tile: '#f8fafb', accent: '#526d91', ink: '#344a64', void: '#b3c5d7' },
    (c, r) => !((r === 0 || r === 8) && c >= 4 && c <= 7)),
  makeMap('courtyard', 'The Courtyard', 'A central plaza changes how chains meet.', 'Central plaza',
    { name: 'Golden garden', canvas: '#f9f1dc', frame: '#ebdcaf', tile: '#fffdf5', accent: '#9c7535', ink: '#67542f', void: '#e3ca89' },
    (c, r) => !(c >= 5 && c <= 6 && r >= 3 && r <= 5)),
  makeMap('peninsulas', 'Peninsulas', 'Narrow northern and southern approaches favor careful mergers.', 'Tapered ends',
    { name: 'Sea glass', canvas: '#e9f4ef', frame: '#cfe3dc', tile: '#f8fcf9', accent: '#428775', ink: '#345f56', void: '#a9d4cb' },
    (c, r) => !((r === 0 || r === 8) && (c < 3 || c > 8))),
  shaped('hourglass', 'The Hourglass', 'Two generous districts meet at a four-tile waist. A merger at the neck can transform the city.', 'Narrow central neck',
    { name: 'Desert dusk', canvas: '#fbebe0', frame: '#ecd0bc', tile: '#fff8ef', accent: '#b46b52', ink: '#704939', void: '#e9bfa9' }, [
      '############', '############', '.##########.', '...######...', '....####....',
      '...######...', '.##########.', '############', '############',
    ]),
  shaped('crossroads', 'Crossroads', 'A broad east–west avenue intersects a compact north–south corridor.', 'Four long arms',
    { name: 'Violet afterglow', canvas: '#f0eaf8', frame: '#dcd0eb', tile: '#fcf9ff', accent: '#8265a9', ink: '#55466b', void: '#c8b4df' }, [
      '...######...', '...######...', '.##########.', '############', '############',
      '############', '.##########.', '...######...', '...######...',
    ]),
  shaped('switchback', 'Switchback', 'The city bends from northwest to southeast, creating winding routes with rotationally fair starts.', 'Winding diagonal',
    { name: 'Alpine trail', canvas: '#eaf3e8', frame: '#cfdfcd', tile: '#f9fcf5', accent: '#587e58', ink: '#3e6149', void: '#a9c8aa' }, [
      '########....', '#########...', '##########..', '..##########', '.##########.',
      '##########..', '..##########', '...#########', '....########',
    ]),
  shaped('atoll', 'The Atoll', 'A wide lagoon splits the middle of the city. Chains can race around either shore.', 'Lagoon ring',
    { name: 'Coral lagoon', canvas: '#e5f5f2', frame: '#bde2dd', tile: '#f7fdfb', accent: '#258c91', ink: '#2e626b', void: '#85cbd0' }, [
      '.##########.', '############', '############', '###......###', '###......###',
      '###......###', '############', '############', '.##########.',
    ]),
  shaped('four-spires', 'Four Spires', 'Four slim towers open onto a crowded central district and many possible merger fronts.', 'Four corner spires',
    { name: 'Midnight & gold', canvas: '#dbe5e8', frame: '#263d56', tile: '#f2f5f1', accent: '#b18d43', ink: '#273f54', void: '#183149' }, [
      '..##....##..', '.##########.', '############', '.##########.', '..########..',
      '.##########.', '############', '.##########.', '..##....##..',
    ]),
  makeSizedMap('twin-docks', 'Twin Docks', 'Two busy waterfronts meet across a long, narrow shipping lane. The middle can turn into a merger corridor.', 'Two docks, one crossing',
    { name: 'Cobalt quay', canvas: '#e8effb', frame: '#b7c8e8', tile: '#f8fbff', accent: '#4274bd', ink: '#2d4c79', void: '#9cb6d9' },
    20, 7, 6, 41, (c, r) => Math.abs(r - 3) <= 1 || c <= 5 || c >= 14),
  makeSizedMap('obelisk', 'The Obelisk', 'A tall, tapered city rewards long vertical chains and careful claims around its narrow tips.', 'Tapered vertical skyline',
    { name: 'Orchid stone', canvas: '#f3edf7', frame: '#d9c8e4', tile: '#fffbff', accent: '#87589b', ink: '#5a3e68', void: '#c3a6d2' },
    11, 17, 6, 53, (c, r) => {
      const width = [5, 5, 7, 7, 9, 9, 11, 11, 11][Math.min(r, 16 - r)];
      return Math.abs(c - 5) <= Math.floor(width / 2);
    }),
  makeSizedMap('coral-crown', 'Coral Crown', 'A sheltered lagoon cuts through a crowned shoreline, sending hotel chains around two lively shores.', 'Crowned lagoon',
    { name: 'Apricot reef', canvas: '#fff0e6', frame: '#efcfbb', tile: '#fffaf4', accent: '#c36743', ink: '#754731', void: '#e4ae8c' },
    14, 12, 6, 52, (c, r) => !(c >= 5 && c <= 8 && r >= 4 && r <= 7)
      && !((c < 2 || c >= 12) && (r < 2 || r >= 10))),
  makeSizedMap('lightning-run', 'Lightning Run', 'A winding diagonal strike bends the city from one edge to the other. Every crossing feels consequential.', 'S-bend lightning corridor',
    { name: 'Electric current', canvas: '#e7f7f6', frame: '#bce0dc', tile: '#fbffff', accent: '#167f86', ink: '#22575e', void: '#83c2c6' },
    18, 9, 6, 45, (c, r) => Math.abs(r - (4 + Math.round(2 * Math.sin((c - 8.5) * Math.PI / 17)))) <= 3),
  makeSizedMap('compass-rose', 'Compass Rose', 'Four broad avenues radiate from a packed central market, with tapered approaches at every point.', 'Four-point city star',
    { name: 'Periwinkle compass', canvas: '#ebeef9', frame: '#ced6ef', tile: '#fbfcff', accent: '#5967b6', ink: '#38416e', void: '#aeb9de' },
    15, 13, 6, 48, (c, r) => Math.abs(c - 7) <= 2 || Math.abs(r - 6) <= 2
      || (Math.abs(c - 7) <= 4 && Math.abs(r - 6) <= 4 && Math.abs(c - 7) + Math.abs(r - 6) <= 7)),
  makeSizedMap('pinwheel', 'The Pinwheel', 'Four offset districts curl around the center. Ownership can grow clockwise or cut across the hub.', 'Four turning districts',
    { name: 'Cherry blossom', canvas: '#fff1f0', frame: '#f0d1d0', tile: '#fffaf8', accent: '#b84f68', ink: '#693d4b', void: '#e8b5bf' },
    15, 14, 6, 52, (c, r) => (c >= 5 && c <= 9 && r >= 4 && r <= 9)
      || (c >= 2 && c <= 6 && r <= 5) || (c >= 9 && r >= 2 && r <= 6)
      || (c >= 8 && c <= 12 && r >= 8) || (c <= 5 && r >= 7 && r <= 11)),
  makeSizedMap('starfall-x', 'Starfall X', 'Four diagonal arms collide in a dense center, making the routes toward a merger unusually direct.', 'Crossed diagonal arms',
    { name: 'Indigo starlight', canvas: '#eae9f8', frame: '#c9c8e8', tile: '#fdfcff', accent: '#6960a9', ink: '#433d72', void: '#a9a4d6' },
    17, 11, 6, 44, (c, r) => Math.abs(r - c * 10 / 16) <= 2.1 || Math.abs(r - (10 - c * 10 / 16)) <= 2.1),
  makeSizedMap('twin-lagoons', 'Twin Lagoons', 'Two neighboring lagoons divide the city into looping shores and a slim shared isthmus.', 'Double-lagoon loops',
    { name: 'Emerald shallows', canvas: '#e2f4e9', frame: '#b4dfc6', tile: '#fafffb', accent: '#2e9364', ink: '#285c47', void: '#8ed0b0' },
    16, 12, 6, 55, (c, r) => !((c >= 3 && c <= 6 || c >= 9 && c <= 12) && r >= 4 && r <= 7)
      && !((c <= 1 || c >= 14) && (r <= 1 || r >= 10))),
  makeSizedMap('big-rectangle', 'Grand Rectangle', 'A wider classic rectangle gives eight investors room to build on every side.', 'Expanded classic grid',
    { name: 'Emerald city', canvas: '#e9f0e6', frame: '#c5d7c1', tile: '#f8fcf6', accent: '#498161', ink: '#315749', void: '#a7c8ae' },
    16, 12, 8, 61, () => true),
  makeSizedMap('big-crater', 'Crater City', 'Eight investors circle a broad central plaza, with mergers racing around its rim.', 'Central crater',
    { name: 'Copper & cream', canvas: '#f7e8db', frame: '#e9c4a8', tile: '#fff8ee', accent: '#ad6942', ink: '#654632', void: '#d99871' },
    16, 12, 8, 61, (c, r) => !(c >= 5 && c <= 10 && r >= 4 && r <= 7)),
  makeSizedMap('big-harbors', 'Twin Harbors', 'Two long central inlets create broad east and west shores linked by a middle boulevard.', 'Twin inlets',
    { name: 'Glacier blue', canvas: '#e8f3f7', frame: '#c3dfea', tile: '#f8fdff', accent: '#4a86a3', ink: '#31566b', void: '#91c9de' },
    16, 12, 8, 61, (c, r) => !((r <= 3 || r >= 8) && c >= 6 && c <= 9)),
  makeSizedMap('big-aurora-gate', 'Aurora Gate', 'An unusually wide northern gateway and two inner sky courts put eight investors on a dramatic ring.', 'Twin sky courts',
    { name: 'Aurora orchid', canvas: '#f1eafa', frame: '#d7c5eb', tile: '#fdfaff', accent: '#a05fa5', ink: '#654d78', void: '#bfa8da' },
    23, 11, 8, 61, (c, r) => {
      const inset = Math.max(0, 4 - Math.min(r, 10 - r));
      return c >= inset && c < 23 - inset && !(c >= 8 && c <= 14 && r >= 3 && r <= 7 && r !== 5);
    }),
  makeSizedMap('big-trident-towers', 'Trident Towers', 'Three tall avenues rise from both sides of a broad city belt, creating separated fronts for eight.', 'Six skyline prongs',
    { name: 'Stormglass blue', canvas: '#e9f1f8', frame: '#bdd0e2', tile: '#fbfdff', accent: '#426e9f', ink: '#2e4b6a', void: '#91b4d4' },
    15, 18, 8, 61, (c, r) => !((r < 6 || r >= 12) && [4, 5, 9, 10].includes(c))
      && !((c < 2 || c >= 13) && (r < 2 || r >= 16))),
  makeSizedMap('mega-diamond', 'Diamond Dominion', 'Ten seats share a sweeping diamond with long diagonal approaches and a broad heart.', 'Clipped diamond',
    { name: 'Amethyst dusk', canvas: '#eeeaf6', frame: '#d2c9e9', tile: '#fbf9ff', accent: '#8068a8', ink: '#51466c', void: '#b7a4d4' },
    20, 14, 10, 81, (c, r) => { const inset = Math.max(0, 4 - Math.min(r, 13 - r)); return c >= inset && c < 20 - inset; }),
  makeSizedMap('mega-rivers', 'Three Rivers', 'Two long waterways divide three trading corridors; the far ends reconnect them.', 'Three land corridors',
    { name: 'Electric tide', canvas: '#e4f4f7', frame: '#b7dce7', tile: '#f7fdfe', accent: '#297f9e', ink: '#2c5668', void: '#76bfd1' },
    20, 14, 10, 81, (c, r) => !(r >= 2 && r <= 11 && [4, 5, 14, 15].includes(c))),
  makeSizedMap('mega-divide', 'The Great Divide', 'A huge central lake and two open gateways turn this ten-seat city into a looping contest.', 'Lake and gateways',
    { name: 'Basalt & mint', canvas: '#e9f0eb', frame: '#9dbbb5', tile: '#f7fcf8', accent: '#427b73', ink: '#325850', void: '#638f8c' },
    20, 14, 10, 81, (c, r) => !(c >= 6 && c <= 13 && r >= 5 && r <= 8) && !((r <= 1 || r >= 12) && c >= 8 && c <= 11)),
  makeSizedMap('mega-triple-arch', 'The Triple Arch', 'Three deep avenues reach inward from both horizons while a busy middle boulevard joins the city.', 'Six carved avenues',
    { name: 'Sunlit bronze', canvas: '#faf1df', frame: '#e7d4a6', tile: '#fffdf7', accent: '#ad7a2e', ink: '#67512e', void: '#dfbe78' },
    27, 13, 10, 81, (c, r) => !((r <= 4 || r >= 8) && (c >= 7 && c <= 10 || c >= 16 && c <= 19))
      && !((c < 2 || c >= 25) && (r < 2 || r >= 11))),
  makeSizedMap('mega-citadel-grid', 'Citadel Grid', 'Four enclosed plazas turn a tall ten-seat city into a lattice of crossroads and looping routes.', 'Four inner plazas',
    { name: 'Mint citadel', canvas: '#e5f4f0', frame: '#b7dad3', tile: '#fbfffd', accent: '#3d8a84', ink: '#2f5d59', void: '#94cbc1' },
    18, 19, 10, 81, (c, r) => !(((c >= 3 && c <= 6 || c >= 11 && c <= 14)
      && (r >= 4 && r <= 7 || r >= 11 && r <= 14)))
      && !((c < 2 || c >= 16) && (r < 2 || r >= 17))),
  makeSizedMap('max-metropolis', 'Metropolis Max', 'A full 24-by-16 skyline stretches the classic rectangular fight to twelve investors.', 'Full megacity grid',
    { name: 'Night market', canvas: '#e6e9ee', frame: '#2d415b', tile: '#f7f8f5', accent: '#be9850', ink: '#30455d', void: '#1d334c' },
    24, 16, 12, 111, () => true),
  makeSizedMap('max-archipelago', 'Grand Archipelago', 'A vast inland sea and four corner bays force twelve investors around a scenic ring.', 'Inland sea and bays',
    { name: 'Aurora coast', canvas: '#e4f4ef', frame: '#acd8cd', tile: '#f7fdfa', accent: '#388b83', ink: '#305e5a', void: '#70c5bd' },
    24, 16, 12, 111, (c, r) => !(c >= 7 && c <= 16 && r >= 5 && r <= 10)
      && !((c <= 3 || c >= 20) && (r <= 1 || r >= 14))),
  makeSizedMap('max-cross', 'The Grand Cross', 'Four sweeping edge cuts leave a crowded center and branching districts for twelve.', 'Four great gateways',
    { name: 'Crimson boulevard', canvas: '#f8e9e7', frame: '#e6c4be', tile: '#fffaf7', accent: '#a95b58', ink: '#674443', void: '#d99d98' },
    24, 16, 12, 111, (c, r) => !((c >= 8 && c <= 15) && (r <= 2 || r >= 13))
      && !((r >= 6 && r <= 9) && (c <= 2 || c >= 21))),
  makeSizedMap('max-celestial-ring', 'Celestial Ring', 'A thirty-column cosmic ring wraps around a vast void, leaving twelve investors two long routes to the far side.', 'Wide galactic hollow',
    { name: 'Rose nebula', canvas: '#f5e9ee', frame: '#dfc2d0', tile: '#fffafd', accent: '#9a576e', ink: '#674552', void: '#cb9faf' },
    30, 17, 12, 111, (c, r) => {
      const inset = Math.max(0, 5 - Math.min(r, 16 - r));
      return c >= inset && c < 30 - inset && !(c >= 9 && c <= 20 && r >= 5 && r <= 11);
    }),
  makeSizedMap('max-orion-star', 'Orion Star', 'Eight vast rays meet in a crowded core; twelve investors can expand outward or converge for a showdown.', 'Eight-point megacity star',
    { name: 'Violet cosmos', canvas: '#eeeaf9', frame: '#d3cbee', tile: '#fdfcff', accent: '#7162bc', ink: '#493e77', void: '#aaa1dd' },
    23, 23, 12, 111, (c, r) => Math.min(Math.abs(c - 11), Math.abs(r - 11)) <= 3
      || Math.abs(Math.abs(c - 11) - Math.abs(r - 11)) <= 2),
];
/** New map IDs are feature-gated online so an older room function cannot accept a selection it does not know. */
export const NEW_MAP_IDS: ReadonlySet<MapId> = new Set([
  'twin-docks', 'obelisk', 'coral-crown', 'lightning-run', 'compass-rose', 'pinwheel', 'starfall-x', 'twin-lagoons',
  'big-aurora-gate', 'big-trident-towers', 'mega-triple-arch', 'mega-citadel-grid', 'max-celestial-ring', 'max-orion-star',
]);
export const getMap = (id: MapId | undefined): MapDefinition => MAPS.find((map) => map.id === id) ?? MAPS[0];
export const isMapId = (value: unknown): value is MapId => typeof value === 'string' && MAPS.some((map) => map.id === value);
export const mapHasTile = (id: MapId | undefined, tile: Tile) => getMap(id).tiles.includes(tile);
